/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout Everywhere
         * @description Revoke every session for the caller, on every device.
         */
        post: operations["logout_everywhere_api_v1_auth_logout_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sign-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign Up
         * @description Create an agency and its owner, then sign them straight in.
         *
         *     Signing in as part of signup is deliberate: requiring a fresh login
         *     immediately after choosing a password is friction with no security value.
         */
        post: operations["sign_up_api_v1_auth_sign_up_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Clients
         * @description Cursor-paginated client list, newest first.
         *
         *     IDs are ULIDs, so `id < cursor ORDER BY id DESC` is a stable, index-backed
         *     window that does not skip or repeat rows when something is inserted
         *     mid-scroll — which for an active prospecting list is the common case.
         */
        get: operations["list_clients_api_v1_clients_get"];
        put?: never;
        /**
         * Create Client
         * @description Submit a URL: creates the client, crawls it, and classifies its industry.
         *
         *     Runs synchronously. §7's acceptance criterion is a classified industry
         *     within 30 seconds of submitting a URL, and the measured path is a few
         *     seconds, so one round trip is both sufficient and simpler than polling.
         *
         *     Set `classify: false` to create the record without spending an LLM call.
         */
        post: operations["create_client_api_v1_clients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{clientId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Client */
        get: operations["get_client_api_v1_clients__clientId__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{clientId}/competitors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Competitors
         * @description The client's most recent competitor set.
         */
        get: operations["get_competitors_api_v1_clients__clientId__competitors_get"];
        /**
         * Replace Competitors
         * @description Replace the competitor set by hand.
         *
         *     This matters more than a normal CRUD override. `Client.industry` confidence
         *     is uncalibrated (build-log Epic 2.6/2.8, Finding 2 — open), so a wrong
         *     classification can seed a poor competitor set, and an operator who knows the
         *     market is the only reliable corrective available today. Everything supplied
         *     here is marked `isManualOverride` and survives later re-detection.
         *
         *     Anything currently in the set and not sent back has been STRUCK, and is
         *     recorded as such — Epic 3 deleted it, which recorded nothing, so the next
         *     detection run reinstated it. See `services.competitors.apply_override`.
         *
         *     `detectionConfidence` is cleared: it measures agreement between two
         *     automated signals, and neither one produced this set. Leaving the previous
         *     value would attach a corroboration claim to rows that were never corroborated.
         */
        put: operations["replace_competitors_api_v1_clients__clientId__competitors_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{clientId}/competitors/detect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Detect Competitors
         * @description Run SERP + AI co-citation discovery and rank the top competitors.
         *
         *     Runs synchronously. A run makes several paid SerpApi searches and several
         *     model calls, so it is explicitly operator-triggered rather than implicit in
         *     intake — an accidental re-detection costs money.
         *
         *     Competitors an operator marked as overrides are preserved across runs.
         */
        post: operations["detect_competitors_api_v1_clients__clientId__competitors_detect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{clientId}/reclassify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reclassify Client
         * @description Re-run crawl and classification for an existing client.
         *
         *     Needed because a site changes, and because an AMBIGUOUS result is often
         *     worth retrying after the operator has looked at the site themselves.
         */
        post: operations["reclassify_client_api_v1_clients__clientId__reclassify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{clientId}/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Scans
         * @description A client's scans, newest first.
         */
        get: operations["list_scans_api_v1_clients__clientId__scans_get"];
        put?: never;
        /**
         * Run Scan
         * @description Queue a scan. Returns immediately; the work happens out of band.
         *
         *     **`202`, not `201`, and `ScanOut`, not `ScanDetailOut`** — Epic 9.5. This
         *     used to run the whole pipeline inline, which Epic 9.2 measured at ~303s, and
         *     Epic 9.3 found the real cost: the scan row sat in an uncommitted transaction
         *     for that entire time, invisible to every other request. There was nothing
         *     for a dashboard to poll because, as far as Postgres was concerned, the scan
         *     did not exist yet.
         *
         *     The response model is `ScanOut` rather than `ScanDetailOut` with empty
         *     fields. At `202` there is no prompt set and there are no results — the
         *     prompt set is generated *by* the scan. Returning `ScanDetailOut` would
         *     describe a shape this endpoint never has, and leave a caller unable to tell
         *     "not generated yet" from "generated, and empty".
         *
         *     Poll `GET /scans/{scanId}` for completion; it carries the prompt set and
         *     results once they exist.
         *
         *     Still costs real money once it runs — 20-30 prompts across every engine plus
         *     a sentiment call per mention. `promptLimit` caps the set for verification.
         *
         *     Reuses the scan Epic 3's competitor detection created, if one is open, so a
         *     detect-then-scan flow does not strand an empty scan.
         */
        post: operations["run_scan_api_v1_clients__clientId__scans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_v1_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness. Deliberately touches no dependency.
         *
         *     A liveness probe that checks the database causes an orchestrator to kill
         *     and restart healthy API pods during a database blip, turning a partial
         *     outage into a total one. Readiness is what should fail then.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness. Verifies the datastores this service cannot serve without.
         */
        get: operations["ready_api_v1_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Public Report
         * @description A report, by share token. **No session required** — Epic 9.8.
         *
         *     This is the send path Epic 9's acceptance criterion needs: the prospect a
         *     report is about has no account, and must not need one to read it.
         *
         *     **The token is the whole credential**, so the rules are narrow and worth
         *     stating:
         *
         *     * **Read-only.** There is no sibling route that mutates anything by token.
         *       A holder cannot edit the competitor set, re-run the scan, or reach any
         *       other scan — the token resolves to exactly one row.
         *     * **`404` for every rejection, with one code path.** A malformed token, an
         *       unknown token and a well-formed miss are indistinguishable in both status
         *       and body. There is no shape or length pre-check, deliberately: rejecting
         *       an implausible token faster than a plausible one is a timing oracle that
         *       makes enumeration cheaper. Every guess pays for the same index lookup.
         *     * **No `401`, ever.** A `401` would say "this token is real, authenticate to
         *       use it", which is precisely the bit an enumerator wants.
         *     * **Same projection as the authenticated route.** `build_report` is reused
         *       rather than reimplemented, so the facts-only guarantee `test_ip_safety.py`
         *       sweeps over this module covers this response too — a second assembly path
         *       would be a second place for a snippet to slip in.
         *
         *     **Errors:** `404` only.
         */
        get: operations["get_public_report_api_v1_reports__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scanId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scan
         * @description A scan with its prompt set and every engine result.
         */
        get: operations["get_scan_api_v1_scans__scanId__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scanId}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Audit
         * @description The scan's technical audit, with every check in display order.
         */
        get: operations["get_audit_api_v1_scans__scanId__audit_get"];
        put?: never;
        /**
         * Run Audit
         * @description Crawl the client's site and record structural signals plus per-check verdicts.
         *
         *     Makes **no model or search calls** — this is a page load plus two side
         *     fetches (robots.txt, sitemap.xml). Cost is bandwidth and a few seconds.
         *
         *     Once an audit exists, re-scoring the scan includes Technical Foundation
         *     instead of excluding it as `NOT_YET_MEASURED`.
         *
         *     One audit per scan, refreshed on re-run: a scan is a point-in-time claim
         *     about a site, so a second audit of the same scan is a correction rather than
         *     a new observation.
         */
        post: operations["run_audit_api_v1_scans__scanId__audit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scanId}/fixes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Fixes
         * @description The scan's fix list as last generated, in rank order.
         *
         *     Returns an empty list with `status: "empty"` rather than 404 when nothing
         *     has been generated yet: "no fixes yet" is a state of a scan that exists,
         *     and the report renders its deterministic list in that case.
         */
        get: operations["get_fixes_api_v1_scans__scanId__fixes_get"];
        put?: never;
        /**
         * Generate Fixes
         * @description Generate the scan's prioritised fix list.
         *
         *     Makes **one model call**. The candidates — which dimension gaps are worth a
         *     line, which audit findings warrant a fix, and in what order — are decided
         *     before the call by the same rules Epic 7 already applies on the client. The
         *     model words them and judges priority and effort; it cannot add a
         *     recommendation the measurement did not produce.
         *
         *     One row per candidate per scan, refreshed on re-run. A regenerated list is a
         *     better statement of the same measurement, not a second measurement — but
         *     `status` is the operator's, so it survives regeneration, and a candidate
         *     that has been worked is kept even once it stops being measured.
         *
         *     A provider failure writes nothing and returns `status: "failed"` with a
         *     reason code. The report still renders its deterministic fix list.
         */
        post: operations["generate_fixes_api_v1_scans__scanId__fixes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scanId}/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Prompt Set
         * @description The scan's generated prompt set.
         */
        get: operations["get_prompt_set_api_v1_scans__scanId__prompts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scanId}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report
         * @description Everything the narrative report needs, in one response.
         *
         *     **Presents; does not compute.** Score, competitors and audit are read from
         *     the rows Epics 3-6 wrote. The only new numbers are aggregates — citation
         *     counts per domain, mention shares, per-engine coverage — and each is a
         *     count over stored facts.
         *
         *     Degraded data is reported, never smoothed over. `score` is null when the
         *     scan was never scored, and a score with `status: "insufficient_data"` is a
         *     different thing again: an unrunnable scan is never rendered as a low score.
         *     `competitorSet` is null when detection never ran, and `audit` is null when
         *     the site was never audited — in each case the report says so rather than
         *     quietly omitting a beat.
         *
         *     **Errors:** `401`, `404` (unknown scan, or another agency's).
         */
        get: operations["get_report_api_v1_scans__scanId__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scanId}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Results
         * @description Cursor-paginated engine results.
         *
         *     Separate from the scan detail because a full scan is 20-30 prompts times
         *     every engine — 60+ rows with nested mentions and citations, which is a lot
         *     to return in one body once a third engine is added.
         */
        get: operations["list_results_api_v1_scans__scanId__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scanId}/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scan Score
         * @description The most recent stored Score for a scan, with the competitor comparison.
         *
         *     The comparison is recomputed from persisted rows on read rather than stored
         *     — it is a pure function of data already in the database, and a second copy
         *     could fall out of step with the first.
         */
        get: operations["get_scan_score_api_v1_scans__scanId__score_get"];
        put?: never;
        /**
         * Compute Scan Score
         * @description Compute and store the AI Visibility Score for a scan.
         *
         *     **Makes no provider calls and costs nothing** — scoring is pure arithmetic
         *     over rows Epic 4 already persisted. Sentiment is read from storage, never
         *     re-classified (scoring-spec.md rule 4), which is what makes re-scoring
         *     reproducible.
         *
         *     **Re-scoring INSERTS a new row** rather than overwriting. A Score is a dated
         *     claim under a named `formulaVersion`; overwriting would erase the history
         *     before/after reporting depends on.
         */
        post: operations["compute_scan_score_api_v1_scans__scanId__score_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scanId}/scores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Scan Scores
         * @description Every Score computed for a scan, newest first.
         *
         *     The audit trail: which `formulaVersion` produced which composite, from which
         *     `inputsDigest`. Two rows sharing a digest but differing in composite mean the
         *     formula changed; differing digests mean the inputs did.
         */
        get: operations["list_scan_scores_api_v1_scans__scanId__scores_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scanId}/share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Share Link
         * @description Mint (or return) the public link for this scan's report — Epic 9.8.
         *
         *     **An explicit action, not a side effect of running a scan.** A scan is a
         *     private measurement until an agency decides otherwise; publishing every
         *     report at creation time and relying on the URL being unknown would make
         *     that decision for them. This is the moment they make it.
         *
         *     **`200`, not `201`, and idempotent.** Calling twice returns the same token
         *     rather than minting a second live link to the same report — there is no
         *     revocation, so every extra token would be a URL nobody is tracking. The
         *     second call creates nothing, so it does not claim to.
         *
         *     **Errors:** `401`, `404` (unknown scan, or another agency's).
         */
        post: operations["create_share_link_api_v1_scans__scanId__share_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionItemListOut
         * @description The scan's fix list, plus what happened the last time it was generated.
         */
        ActionItemListOut: {
            /** Generatedby */
            generatedBy?: string | null;
            /** Items */
            items?: components["schemas"]["ActionItemOut"][];
            /** Reasoncode */
            reasonCode?: string | null;
            /** Scanid */
            scanId: string;
            /** Status */
            status: string;
        };
        /**
         * ActionItemOut
         * @description One generated fix — §5.3's prioritised action list.
         */
        ActionItemOut: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Detail */
            detail?: string | null;
            /** Dimensionkey */
            dimensionKey?: string | null;
            effort: components["schemas"]["Effort"];
            /** Generatedby */
            generatedBy?: string | null;
            /** Id */
            id: string;
            /** Pointsupside */
            pointsUpside?: string | null;
            priority: components["schemas"]["Priority"];
            /** Rank */
            rank: number;
            /** Scanid */
            scanId: string;
            source: components["schemas"]["ActionItemSource"];
            /** Sourcekey */
            sourceKey: string;
            status: components["schemas"]["ActionItemStatus"];
            /** Title */
            title: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /**
         * ActionItemSource
         * @description Which Epic 7 candidate produced this fix.
         *
         *     Deliberately only two members. An LLM-authored fix is not a third source —
         *     it is the same measured gap or audit finding, worded better, and modelling
         *     it as its own source would let a generated recommendation exist without a
         *     measurement behind it.
         * @enum {string}
         */
        ActionItemSource: "gap" | "audit";
        /**
         * ActionItemStatus
         * @enum {string}
         */
        ActionItemStatus: "open" | "in_progress" | "done" | "dismissed";
        /** AgencyOut */
        AgencyOut: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Seatlimit */
            seatLimit: number;
            /** Slug */
            slug: string;
        };
        /**
         * AuditCheckOut
         * @description One check's verdict — §7's "pass/fail + detail for each check".
         */
        AuditCheckOut: {
            /** Checkkey */
            checkKey: string;
            /** Detailcode */
            detailCode?: string | null;
            /** Id */
            id: string;
            status: components["schemas"]["CheckStatus"];
            /** Value */
            value?: string | null;
        };
        /**
         * AuditStatus
         * @description Outcome of an audit run.
         *
         *     Added in Epic 6. Without it a failed crawl and a genuinely bare site are
         *     indistinguishable — both would be a row of nulls — and the Technical
         *     Foundation sub-score must never treat "we could not read the site" as
         *     "the site has no markup". Same discipline as ClassificationStatus,
         *     DetectionStatus and ScoreStatus.
         * @enum {string}
         */
        AuditStatus: "ok" | "partial" | "failed";
        /** BrandMentionOut */
        BrandMentionOut: {
            /** Competitorid */
            competitorId?: string | null;
            /** Entitydomain */
            entityDomain?: string | null;
            /** Entityname */
            entityName: string;
            /** Id */
            id: string;
            /** Issubject */
            isSubject: boolean;
            /** Position */
            position?: number | null;
        };
        /**
         * CheckStatus
         * @enum {string}
         */
        CheckStatus: "pass" | "warn" | "fail" | "not_applicable" | "error";
        /** CitationOut */
        CitationOut: {
            /** Citessubject */
            citesSubject: boolean;
            /** Competitorid */
            competitorId?: string | null;
            /** Id */
            id: string;
            /** Position */
            position?: number | null;
            /** Sourcedomain */
            sourceDomain: string;
            sourceType: components["schemas"]["CitationType"];
            /** Sourceurl */
            sourceUrl?: string | null;
        };
        /**
         * CitationType
         * @enum {string}
         */
        CitationType: "owned" | "competitor" | "directory" | "review" | "editorial" | "social" | "other";
        /**
         * CitedDomainOut
         * @description A domain an engine cited, and how often.
         *
         *     Domain + URL + count. api-contracts.md and ip-safety.md #7 both permit
         *     cited domains and URLs explicitly; the cited PAGE's text is never read,
         *     stored, or shown. `sample_url` is a link out to the source — the sanctioned
         *     alternative to quoting it.
         */
        CitedDomainOut: {
            /** Citations */
            citations: number;
            /** Citessubject */
            citesSubject: boolean;
            /** Competitorname */
            competitorName?: string | null;
            /** Domain */
            domain: string;
            /** Sampleurl */
            sampleUrl?: string | null;
        };
        /**
         * ClassificationStatus
         * @description Outcome of Epic 2's industry classification.
         *
         *     Deliberately mirrors Score.status (scoring-spec.md): a result we could not
         *     determine is recorded as such, never as a confident-looking guess.
         * @enum {string}
         */
        ClassificationStatus: "pending" | "classified" | "ambiguous" | "unclassifiable";
        /**
         * ClientDetailOut
         * @description A client plus the crawl facts from its most recent classification.
         */
        ClientDetailOut: {
            /** Agencyid */
            agencyId: string;
            /** Brandname */
            brandName?: string | null;
            /** Classificationreasoncode */
            classificationReasonCode?: string | null;
            classificationStatus: components["schemas"]["ClassificationStatus"];
            /** Classifiedat */
            classifiedAt?: string | null;
            /** Classifiermodel */
            classifierModel?: string | null;
            crawl?: components["schemas"]["CrawlSummaryOut"] | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Domain */
            domain: string;
            /** Id */
            id: string;
            /** Industry */
            industry?: string | null;
            /** Industryconfidence */
            industryConfidence?: string | null;
            /** Industryconfidencescore */
            industryConfidenceScore?: string | null;
            /** Industryniche */
            industryNiche?: string | null;
            kind: components["schemas"]["ClientKind"];
            /** Name */
            name: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /**
         * ClientKind
         * @description A prospect becomes a client when the deal closes.
         *
         *     The same row transitions rather than being recreated, so the scan history
         *     gathered while prospecting becomes the "before" half of the before/after
         *     ROI report in Epic 11.
         * @enum {string}
         */
        ClientKind: "prospect" | "client" | "churned";
        /** ClientOut */
        ClientOut: {
            /** Agencyid */
            agencyId: string;
            /** Brandname */
            brandName?: string | null;
            /** Classificationreasoncode */
            classificationReasonCode?: string | null;
            classificationStatus: components["schemas"]["ClassificationStatus"];
            /** Classifiedat */
            classifiedAt?: string | null;
            /** Classifiermodel */
            classifierModel?: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Domain */
            domain: string;
            /** Id */
            id: string;
            /** Industry */
            industry?: string | null;
            /** Industryconfidence */
            industryConfidence?: string | null;
            /** Industryconfidencescore */
            industryConfidenceScore?: string | null;
            /** Industryniche */
            industryNiche?: string | null;
            kind: components["schemas"]["ClientKind"];
            /** Name */
            name: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /**
         * CompetitorInput
         * @description One competitor in an operator's replacement set.
         */
        CompetitorInput: {
            /** Domain */
            domain?: string | null;
            /** Name */
            name: string;
        };
        /** CompetitorOut */
        CompetitorOut: {
            /** Cocitationmentions */
            coCitationMentions: number;
            /** Corroborated */
            corroborated: boolean;
            detectionSource: components["schemas"]["DetectionSource"];
            /** Domain */
            domain?: string | null;
            /** Id */
            id: string;
            /** Ismanualoverride */
            isManualOverride: boolean;
            /** Name */
            name: string;
            /** Rank */
            rank: number;
            /** Score */
            score?: string | null;
            /** Serpmentions */
            serpMentions: number;
            /** Signalcount */
            signalCount: number;
        };
        /**
         * CompetitorScoreOut
         * @description Per-competitor figures for the three measurable dimensions.
         *
         *     **There is deliberately no `composite`.** Sentiment is classified toward the
         *     subject only (Epic 4.3) and Technical Foundation arrives in Epic 6, so 25%
         *     of the weight has no per-competitor input. A composite computed over a
         *     different weight basis would not be comparable to the subject's, which is
         *     the entire purpose of a comparison.
         */
        CompetitorScoreOut: {
            /** Citationstrength */
            citationStrength: string;
            /** Competitorid */
            competitorId: string;
            /** Mentionrate */
            mentionRate: string;
            /** Name */
            name: string;
            /** Shareofvoice */
            shareOfVoice: string;
        };
        /** CompetitorSetOut */
        CompetitorSetOut: {
            /** Candidatesconsidered */
            candidatesConsidered: number;
            /** Cocitationpromptsrun */
            coCitationPromptsRun: number;
            /** Competitors */
            competitors?: components["schemas"]["CompetitorOut"][];
            /**
             * Confidencecovers
             * @default 0
             */
            confidenceCovers: number;
            /** Detectedat */
            detectedAt?: string | null;
            /** Detectionconfidence */
            detectionConfidence?: string | null;
            /** Id */
            id: string;
            /** Scanid */
            scanId: string;
            /** Serpqueriesrun */
            serpQueriesRun: number;
            status: components["schemas"]["DetectionStatus"];
            /** Usedindustryseed */
            usedIndustrySeed: boolean;
        };
        /**
         * CrawlSummaryOut
         * @description FACTS from the crawl. Never page content — see services/crawl.py.
         */
        CrawlSummaryOut: {
            /** Detectedlanguage */
            detectedLanguage?: string | null;
            /** H1Count */
            h1Count: number;
            /** Hasmetadescription */
            hasMetaDescription: boolean;
            /** Hastitle */
            hasTitle: boolean;
            /** Pagesfetched */
            pagesFetched: number;
            /** Schematypes */
            schemaTypes: string[];
            /** Urlsfetched */
            urlsFetched: string[];
            /** Wordcount */
            wordCount: number;
        };
        /**
         * CreateClientRequest
         * @description Intake payload.
         *
         *     `url` is intentionally permissive — an operator pastes whatever they have,
         *     including a bare domain. Normalisation and validation happen server-side in
         *     services/intake.py:parse_domain so the browser and the API cannot disagree
         *     about what counts as a valid address.
         */
        CreateClientRequest: {
            /**
             * Classify
             * @default true
             */
            classify: boolean;
            /** Name */
            name?: string | null;
            /** Url */
            url: string;
        };
        /** DashboardOut */
        DashboardOut: {
            agency: components["schemas"]["AgencyOut"];
            /** Clientcount */
            clientCount: number;
            /** Isempty */
            isEmpty: boolean;
            /** Recentscans */
            recentScans: components["schemas"]["ScanSummaryOut"][];
            /** Scancount */
            scanCount: number;
            seats: components["schemas"]["SeatUsageOut"];
        };
        /**
         * DetectionSource
         * @enum {string}
         */
        DetectionSource: "serp" | "co_citation" | "both" | "manual";
        /**
         * DetectionStatus
         * @description Outcome of a competitor-detection run.
         *
         *     Mirrors ClassificationStatus and Score's INSUFFICIENT_DATA: a detection we
         *     could not make confidently must be representable as such, rather than
         *     surfacing a thin or contradictory set as though it were a finding.
         * @enum {string}
         */
        DetectionStatus: "ok" | "weak_signal" | "no_signal";
        /**
         * Effort
         * @enum {string}
         */
        Effort: "S" | "M" | "L";
        /**
         * Engine
         * @description AI answer engines. §7 Epic 4 starts with two, behind a common interface.
         * @enum {string}
         */
        Engine: "chatgpt" | "perplexity" | "google_ai_overview" | "gemini" | "claude" | "claude_search" | "copilot";
        /**
         * EngineCoverageOut
         * @description How one engine covered the prompt set. Counts only.
         */
        EngineCoverageOut: {
            /** Answered */
            answered: number;
            engine: components["schemas"]["Engine"];
            /** Mentioned */
            mentioned: number;
            /** Promptsrun */
            promptsRun: number;
        };
        /** EngineResultOut */
        EngineResultOut: {
            /** Brandmentions */
            brandMentions?: components["schemas"]["BrandMentionOut"][];
            /** Brandsmentioned */
            brandsMentioned: number;
            /** Citations */
            citations?: components["schemas"]["CitationOut"][];
            engine: components["schemas"]["Engine"];
            /** Engineversion */
            engineVersion?: string | null;
            /** Errorcode */
            errorCode?: string | null;
            /** Id */
            id: string;
            /** Latencyms */
            latencyMs?: number | null;
            /** Mentioned */
            mentioned: boolean;
            /** Position */
            position?: number | null;
            /** Prominence */
            prominence?: string | null;
            /** Promptid */
            promptId: string;
            /** Responsedigest */
            responseDigest?: string | null;
            sentiment?: components["schemas"]["Sentiment"] | null;
            /** Sentimentconfidence */
            sentimentConfidence?: string | null;
            status: components["schemas"]["EngineResultStatus"];
        };
        /**
         * EngineResultStatus
         * @enum {string}
         */
        EngineResultStatus: "ok" | "answered_no_mention" | "rate_limited" | "error" | "timeout";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MeOut
         * @description The whole authenticated context in one call.
         *
         *     The web app needs user, agency, and seat usage to render its shell. Serving
         *     them together avoids three round trips on every page load.
         */
        MeOut: {
            agency: components["schemas"]["AgencyOut"];
            seats: components["schemas"]["SeatUsageOut"];
            user: components["schemas"]["UserOut"];
        };
        /**
         * MentionShareOut
         * @description One brand's share of the mentions in this scan.
         *
         *     Entity NAMES are facts and are explicitly permitted. `outranks_subject` is
         *     arithmetic over stored ordinals, not a judgement.
         */
        MentionShareOut: {
            /** Appearances */
            appearances: number;
            /** Bestposition */
            bestPosition?: number | null;
            /** Entitydomain */
            entityDomain?: string | null;
            /** Entityname */
            entityName: string;
            /** Issubject */
            isSubject: boolean;
            /** Outrankssubject */
            outranksSubject: boolean;
        };
        /** Page[ClientOut] */
        Page_ClientOut_: {
            /** Data */
            data: components["schemas"]["ClientOut"][];
            /** Nextcursor */
            nextCursor?: string | null;
        };
        /** Page[EngineResultOut] */
        Page_EngineResultOut_: {
            /** Data */
            data: components["schemas"]["EngineResultOut"][];
            /** Nextcursor */
            nextCursor?: string | null;
        };
        /** Page[ScanOut] */
        Page_ScanOut_: {
            /** Data */
            data: components["schemas"]["ScanOut"][];
            /** Nextcursor */
            nextCursor?: string | null;
        };
        /**
         * Priority
         * @enum {string}
         */
        Priority: "high" | "medium" | "low";
        /**
         * PromptIntent
         * @description Buyer-journey stage. §7 Epic 4 requires intent tagging.
         * @enum {string}
         */
        PromptIntent: "awareness" | "comparison" | "bottom_funnel";
        /** PromptOut */
        PromptOut: {
            /** Id */
            id: string;
            intent: components["schemas"]["PromptIntent"];
            /** Position */
            position: number;
            /** Text */
            text: string;
        };
        /** PromptSetOut */
        PromptSetOut: {
            /** Generatedby */
            generatedBy?: string | null;
            /** Generationparams */
            generationParams?: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
            /** Prompts */
            prompts?: components["schemas"]["PromptOut"][];
            /** Scanid */
            scanId: string;
        };
        /**
         * PromptShelfOut
         * @description One answer, as the ordered shelf of brands it named — Epic 7.1.
         *
         *     Direction A of `design-direction.md` §5. The report's aggregate tables
         *     answer "how often overall"; this answers "in THIS question, who stood
         *     where, and were you there at all". The subject's absence is a fact this
         *     row carries explicitly (`subject_present: false`) rather than an entry
         *     that is merely missing, because the visualisation draws absence as an
         *     empty notch and a silently absent row would draw nothing.
         *
         *     On `prompt_text` — ip-safety.md #7 governs scraped and model-returned
         *     content ABOUT third parties. This is OUR OWN generated question, the same
         *     field `PromptOut.text` has returned on `/scans/{id}/prompts` since Epic 4,
         *     and the exception is registered by name in `test_ip_safety.py` rather than
         *     left to dodge the forbidden-field sweep by luck.
         */
        PromptShelfOut: {
            /** Answered */
            answered: boolean;
            engine: components["schemas"]["Engine"];
            /** Promptid */
            promptId: string;
            /** Promptposition */
            promptPosition: number;
            /** Prompttext */
            promptText: string;
            /** Slots */
            slots: components["schemas"]["ShelfSlotOut"][];
            /**
             * Subjectcited
             * @default false
             */
            subjectCited: boolean;
            /** Subjectposition */
            subjectPosition?: number | null;
            /** Subjectpresent */
            subjectPresent: boolean;
        };
        /** ReadyOut */
        ReadyOut: {
            /** Checks */
            checks: {
                [key: string]: string;
            };
            /** Status */
            status: string;
        };
        /**
         * ReplaceCompetitorsRequest
         * @description Operator override for a detected competitor set.
         *
         *     Replaces the set wholesale rather than patching individual rows: an operator
         *     correcting a bad detection is expressing "these are the rivals", and
         *     reconciling that against auto-detected rows one at a time invites a
         *     half-applied state where the correction is neither in force nor discarded.
         *
         *     Every competitor supplied here is marked `isManualOverride`, which protects
         *     it from being removed by a later re-detection.
         */
        ReplaceCompetitorsRequest: {
            /** Competitors */
            competitors?: components["schemas"]["CompetitorInput"][];
        };
        /**
         * ReportAgencyOut
         * @description The white-label surface.
         *
         *     Name and slug only. Logo, custom domain and brand colours are §7 line 2 and
         *     are deferred to Epic 7.1 — they need new columns AND a written policy on
         *     which tokens an agency may override, because the visibility ramp is
         *     load-bearing: an agency free to recolour it changes what the score means.
         */
        ReportAgencyOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /**
         * ReportAuditFindingOut
         * @description An audit check the report can act on.
         *
         *     Same shape as `AuditCheckOut` — a machine `detail_code`, never prose. The
         *     fix beat maps the code to concrete copy from our own string table.
         */
        ReportAuditFindingOut: {
            /** Checkkey */
            checkKey: string;
            /** Detailcode */
            detailCode?: string | null;
            /** Id */
            id: string;
            status: components["schemas"]["CheckStatus"];
            /** Value */
            value?: string | null;
        };
        /** ReportAuditOut */
        ReportAuditOut: {
            /** Auditedat */
            auditedAt?: string | null;
            /** Errorcode */
            errorCode?: string | null;
            /** Failed */
            failed: number;
            /** Findings */
            findings: components["schemas"]["ReportAuditFindingOut"][];
            /** Notapplicable */
            notApplicable: number;
            /** Passed */
            passed: number;
            status: components["schemas"]["AuditStatus"];
            /** Technicalfoundation */
            technicalFoundation?: string | null;
            /** Urlaudited */
            urlAudited?: string | null;
            /** Warned */
            warned: number;
        };
        /**
         * ReportCompetitorOut
         * @description A detected competitor plus its comparable sub-scores.
         *
         *     **No composite, deliberately.** Sentiment is classified toward the subject
         *     only and Technical Foundation is the subject's own site, so 25% of the
         *     weight has no per-competitor input. A "competitor composite" over the
         *     remaining 75% would not be comparable to the subject's — it would read as a
         *     competitor scoring lower than they do. The report compares per-dimension
         *     instead, on the three dimensions that genuinely have both sides.
         *
         *     Null sub-scores mean the scan produced no comparison for this competitor.
         */
        ReportCompetitorOut: {
            /** Citationstrength */
            citationStrength?: string | null;
            /** Cocitationmentions */
            coCitationMentions: number;
            /** Corroborated */
            corroborated: boolean;
            detectionSource: components["schemas"]["DetectionSource"];
            /** Domain */
            domain?: string | null;
            /** Id */
            id: string;
            /** Ismanualoverride */
            isManualOverride: boolean;
            /** Mentionrate */
            mentionRate?: string | null;
            /** Name */
            name: string;
            /** Rank */
            rank: number;
            /** Score */
            score?: string | null;
            /** Serpmentions */
            serpMentions: number;
            /** Shareofvoice */
            shareOfVoice?: string | null;
            /** Signalcount */
            signalCount: number;
        };
        /** ReportCompetitorSetOut */
        ReportCompetitorSetOut: {
            /** Competitors */
            competitors: components["schemas"]["ReportCompetitorOut"][];
            /**
             * Confidencecovers
             * @default 0
             */
            confidenceCovers: number;
            /** Detectionconfidence */
            detectionConfidence?: string | null;
            /** Status */
            status: string;
        };
        /**
         * ReportDimensionOut
         * @description One §6 dimension as the report needs it.
         *
         *     `key` is a stable machine key; the human label lives in the frontend string
         *     table, matching how `detail_code` is handled (api-contracts.md, Epic 6).
         *
         *     An EXCLUDED dimension carries `included: false`, a null `subscore`, and the
         *     reason. It is never emitted as `subscore: 0` — the whole point of
         *     `excluded_dimensions` is that "nothing to measure" and "measured, scored
         *     zero" are different claims about a client.
         */
        ReportDimensionOut: {
            /** Exclusionreason */
            exclusionReason?: string | null;
            /** Included */
            included: boolean;
            /** Key */
            key: string;
            /** Subscore */
            subscore?: string | null;
            /** Weight */
            weight: string;
        };
        /**
         * ReportOut
         * @description Everything the five narrative beats need, in one response.
         */
        ReportOut: {
            /** Actionitems */
            actionItems?: components["schemas"]["ActionItemOut"][];
            agency: components["schemas"]["ReportAgencyOut"];
            audit: components["schemas"]["ReportAuditOut"] | null;
            competitorSet: components["schemas"]["ReportCompetitorSetOut"] | null;
            /** Dimensions */
            dimensions: components["schemas"]["ReportDimensionOut"][];
            /**
             * Generatedat
             * Format: date-time
             */
            generatedAt: string;
            proof: components["schemas"]["ReportProofOut"];
            /** Scanid */
            scanId: string;
            /** Scanstatus */
            scanStatus: string;
            /** Scannedat */
            scannedAt?: string | null;
            score: components["schemas"]["ScoreDetailOut"] | null;
            subject: components["schemas"]["ReportSubjectOut"];
        };
        /**
         * ReportProofOut
         * @description The evidence beat's raw material — all of it aggregated counts.
         *
         *     This is the surface ip-safety.md #7 is most exposed on, because it is the
         *     first time collected facts are RENDERED rather than stored. There is no
         *     field here that could hold an engine's prose, and there is nothing upstream
         *     to fill one with: `engine_results` has no text-bearing column at all.
         */
        ReportProofOut: {
            /** Answeredresults */
            answeredResults: number;
            /** Competitorciteddomains */
            competitorCitedDomains: components["schemas"]["CitedDomainOut"][];
            /** Enginecoverage */
            engineCoverage: components["schemas"]["EngineCoverageOut"][];
            /** Engineresults */
            engineResults: number;
            /** Mentionshares */
            mentionShares: components["schemas"]["MentionShareOut"][];
            /** Promptshelf */
            promptShelf?: components["schemas"]["PromptShelfOut"][];
            /** Promptsrun */
            promptsRun: number;
            /** Resultsmentioningsubject */
            resultsMentioningSubject: number;
            /** Subjectcitations */
            subjectCitations: number;
            /** Subjectciteddomains */
            subjectCitedDomains: components["schemas"]["CitedDomainOut"][];
            /** Totalcitations */
            totalCitations: number;
            /** Unclaimedciteddomains */
            unclaimedCitedDomains?: components["schemas"]["CitedDomainOut"][];
        };
        /**
         * ReportSubjectOut
         * @description Who the report is about. Facts from Client (Epic 2).
         */
        ReportSubjectOut: {
            /** Brandname */
            brandName?: string | null;
            /** Clientid */
            clientId: string;
            /** Domain */
            domain: string;
            /** Industry */
            industry?: string | null;
            /** Industryniche */
            industryNiche?: string | null;
            /** Name */
            name: string;
        };
        /**
         * RunScanRequest
         * @description Start a scan.
         *
         *     `promptLimit` caps the generated set. It exists for cost control during
         *     verification — a full run is 20-30 prompts across every engine, and the
         *     grounded engine can take 100s per prompt. Omit it for a real scan.
         */
        RunScanRequest: {
            /** Engines */
            engines?: components["schemas"]["Engine"][] | null;
            /** Promptlimit */
            promptLimit?: number | null;
        };
        /** ScanDetailOut */
        ScanDetailOut: {
            /** Agencyid */
            agencyId: string;
            /** Clientid */
            clientId: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Engineresultcount */
            engineResultCount: number;
            /** Engineversions */
            engineVersions?: {
                [key: string]: unknown;
            };
            /** Errorcode */
            errorCode?: string | null;
            /** Finishedat */
            finishedAt?: string | null;
            /** Formulaversion */
            formulaVersion: string;
            /** Id */
            id: string;
            /** Promptcount */
            promptCount: number;
            promptSet?: components["schemas"]["PromptSetOut"] | null;
            /** Results */
            results?: components["schemas"]["EngineResultOut"][];
            /** Startedat */
            startedAt?: string | null;
            status: components["schemas"]["ScanStatus"];
            trigger: components["schemas"]["ScanTrigger"];
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** ScanOut */
        ScanOut: {
            /** Agencyid */
            agencyId: string;
            /** Clientid */
            clientId: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Engineresultcount */
            engineResultCount: number;
            /** Engineversions */
            engineVersions?: {
                [key: string]: unknown;
            };
            /** Errorcode */
            errorCode?: string | null;
            /** Finishedat */
            finishedAt?: string | null;
            /** Formulaversion */
            formulaVersion: string;
            /** Id */
            id: string;
            /** Promptcount */
            promptCount: number;
            /** Startedat */
            startedAt?: string | null;
            status: components["schemas"]["ScanStatus"];
            trigger: components["schemas"]["ScanTrigger"];
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /**
         * ScanStatus
         * @enum {string}
         */
        ScanStatus: "queued" | "running" | "succeeded" | "partial" | "failed" | "cancelled";
        /** ScanSummaryOut */
        ScanSummaryOut: {
            /** Clientdomain */
            clientDomain: string;
            /** Clientid */
            clientId: string;
            /** Clientname */
            clientName: string;
            /** Compositescore */
            compositeScore?: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Finishedat */
            finishedAt?: string | null;
            /** Id */
            id: string;
            status: components["schemas"]["ScanStatus"];
        };
        /**
         * ScanTrigger
         * @enum {string}
         */
        ScanTrigger: "manual" | "scheduled" | "bulk";
        /** ScoreDetailOut */
        ScoreDetailOut: {
            /** Citationstrength */
            citationStrength?: string | null;
            /** Competitors */
            competitors?: components["schemas"]["CompetitorScoreOut"][];
            /** Composite */
            composite?: string | null;
            /** Computedat */
            computedAt?: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Degradationflags */
            degradationFlags?: string[];
            /** Excludeddimensions */
            excludedDimensions?: {
                [key: string]: unknown;
            };
            /** Formulaversion */
            formulaVersion: string;
            /** Id */
            id: string;
            /** Inputsdigest */
            inputsDigest?: string | null;
            /** Mentionrate */
            mentionRate?: string | null;
            /** Reasoncode */
            reasonCode?: string | null;
            /** Scanid */
            scanId: string;
            /** Sentiment */
            sentiment?: string | null;
            /** Shareofvoice */
            shareOfVoice?: string | null;
            status: components["schemas"]["ScoreStatus"];
            /** Technicalfoundation */
            technicalFoundation?: string | null;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** Weights */
            weights?: {
                [key: string]: unknown;
            };
        };
        /** ScoreOut */
        ScoreOut: {
            /** Citationstrength */
            citationStrength?: string | null;
            /** Composite */
            composite?: string | null;
            /** Computedat */
            computedAt?: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Degradationflags */
            degradationFlags?: string[];
            /** Excludeddimensions */
            excludedDimensions?: {
                [key: string]: unknown;
            };
            /** Formulaversion */
            formulaVersion: string;
            /** Id */
            id: string;
            /** Inputsdigest */
            inputsDigest?: string | null;
            /** Mentionrate */
            mentionRate?: string | null;
            /** Reasoncode */
            reasonCode?: string | null;
            /** Scanid */
            scanId: string;
            /** Sentiment */
            sentiment?: string | null;
            /** Shareofvoice */
            shareOfVoice?: string | null;
            status: components["schemas"]["ScoreStatus"];
            /** Technicalfoundation */
            technicalFoundation?: string | null;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** Weights */
            weights?: {
                [key: string]: unknown;
            };
        };
        /**
         * ScoreStatus
         * @enum {string}
         */
        ScoreStatus: "scored" | "insufficient_data";
        /** SeatUsageOut */
        SeatUsageOut: {
            /** Limit */
            limit: number;
            /** Used */
            used: number;
        };
        /**
         * Sentiment
         * @enum {string}
         */
        Sentiment: "positive" | "neutral" | "negative";
        /**
         * ShareLinkOut
         * @description The public link for a report — Epic 9.8.
         *
         *     Carries the complete URL, not just the token, because the operator's next
         *     action is to paste it into an email. Returning a bare token would force
         *     every caller to rebuild the same string, which is how a frontend and a
         *     backend end up disagreeing about a path.
         *
         *     `token` is exposed alongside it deliberately: it is the operator's OWN
         *     capability for their OWN scan, already implied by the URL beside it, and
         *     tests assert on it without having to parse a URL apart.
         */
        ShareLinkOut: {
            /** Scanid */
            scanId: string;
            /** Token */
            token: string;
            /** Url */
            url: string;
        };
        /**
         * ShelfSlotOut
         * @description One brand standing in one ordinal slot of one answer.
         *
         *     ip-safety.md #7 names exactly this shape as permitted: "counts and ordinal
         *     positions (e.g. 'mentioned 3rd')" plus "names of entities mentioned". There
         *     is no field here that could carry what the answer SAID about the brand —
         *     only that it named it, and where in the order.
         */
        ShelfSlotOut: {
            /**
             * Cited
             * @default false
             */
            cited: boolean;
            /** Competitorname */
            competitorName?: string | null;
            /** Entitydomain */
            entityDomain?: string | null;
            /** Entityname */
            entityName: string;
            /** Issubject */
            isSubject: boolean;
            /** Position */
            position: number;
        };
        /** SignUpRequest */
        SignUpRequest: {
            /** Agencyname */
            agencyName: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Fullname */
            fullName: string;
            /** Password */
            password: string;
        };
        /** TechnicalAuditOut */
        TechnicalAuditOut: {
            /** Auditedat */
            auditedAt?: string | null;
            /** Canonicalpresent */
            canonicalPresent: boolean;
            /** Checks */
            checks?: components["schemas"]["AuditCheckOut"][];
            /** Cls */
            cls?: string | null;
            /** Contentagedays */
            contentAgeDays?: number | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Errorcode */
            errorCode?: string | null;
            /** Excludedcomponents */
            excludedComponents?: {
                [key: string]: unknown;
            };
            /** H1Count */
            h1Count: number;
            /** Hasfaqschema */
            hasFaqSchema: boolean;
            /** Haslocalbusinessschema */
            hasLocalbusinessSchema: boolean;
            /** Hasorganizationschema */
            hasOrganizationSchema: boolean;
            /** Hasproductschema */
            hasProductSchema: boolean;
            /** Hassitemap */
            hasSitemap: boolean;
            /** Id */
            id: string;
            /** Inpms */
            inpMs?: number | null;
            /** Isindexable */
            isIndexable: boolean;
            /** Lcpms */
            lcpMs?: number | null;
            /** Pagescrawled */
            pagesCrawled: number;
            /** Robotsallowscrawl */
            robotsAllowsCrawl: boolean;
            /** Scanid */
            scanId: string;
            /** Schematypes */
            schemaTypes?: string[];
            status: components["schemas"]["AuditStatus"];
            /** Technicalfoundation */
            technicalFoundation?: string | null;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** Urlaudited */
            urlAudited: string;
            /** Wordcount */
            wordCount: number;
        };
        /** UserOut */
        UserOut: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Email */
            email: string;
            /** Fullname */
            fullName: string;
            /** Id */
            id: string;
            /** Lastloginat */
            lastLoginAt?: string | null;
            role: components["schemas"]["UserRole"];
            status: components["schemas"]["UserStatus"];
        };
        /**
         * UserRole
         * @description Seat roles.
         *
         *     OWNER is the billing contact and cannot be removed while it is the last
         *     owner — an agency with no owner has nobody who can manage seats.
         * @enum {string}
         */
        UserRole: "owner" | "admin" | "member";
        /**
         * UserStatus
         * @enum {string}
         */
        UserStatus: "active" | "invited" | "suspended";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout_everywhere_api_v1_auth_logout_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    sign_up_api_v1_auth_sign_up_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_clients_api_v1_clients_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ClientOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_client_api_v1_clients_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClientRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_client_api_v1_clients__clientId__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_competitors_api_v1_clients__clientId__competitors_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitorSetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_competitors_api_v1_clients__clientId__competitors_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceCompetitorsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitorSetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detect_competitors_api_v1_clients__clientId__competitors_detect_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitorSetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reclassify_client_api_v1_clients__clientId__reclassify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scans_api_v1_clients__clientId__scans_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                clientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ScanOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_scan_api_v1_clients__clientId__scans_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_api_v1_dashboard_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    ready_api_v1_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyOut"];
                };
            };
        };
    };
    get_public_report_api_v1_reports__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan_api_v1_scans__scanId__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scanId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_api_v1_scans__scanId__audit_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scanId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechnicalAuditOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_audit_api_v1_scans__scanId__audit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scanId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechnicalAuditOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fixes_api_v1_scans__scanId__fixes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scanId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionItemListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_fixes_api_v1_scans__scanId__fixes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scanId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionItemListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_prompt_set_api_v1_scans__scanId__prompts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scanId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptSetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_api_v1_scans__scanId__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scanId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_results_api_v1_scans__scanId__results_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                scanId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_EngineResultOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan_score_api_v1_scans__scanId__score_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scanId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compute_scan_score_api_v1_scans__scanId__score_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scanId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scan_scores_api_v1_scans__scanId__scores_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scanId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_share_link_api_v1_scans__scanId__share_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scanId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareLinkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
