"""Schema-level enforcement of docs/ip-safety.md constraint 7.

"Scraped data from AI engines or competitor pages is for FACTS ONLY... Never
store, render, or republish a competitor's actual copyrighted text."

These tests make that a build failure rather than a review comment. If someone
adds a `raw_response` column to EngineResult in eighteen months, CI stops them.
"""

from __future__ import annotations

import pytest
from sqlalchemy import String, Text

from avp_api.models import (
    Base,
    BrandMention,
    Citation,
    Client,
    Competitor,
    EngineResult,
    TechnicalAudit,
    TechnicalAuditCheck,
)

# Tables holding data derived from third-party sources (AI engine answers,
# competitor pages). These may hold facts only.
FACTS_ONLY_MODELS = [
    EngineResult,
    Citation,
    BrandMention,
    Competitor,
    TechnicalAudit,
    TechnicalAuditCheck,
    # Added in Epic 2. The intake crawl fetches a prospect's pages, so Client
    # is now downstream of third-party content and must obey the same rule:
    # what it stores is the CONCLUSION (industry label, niche, brand name,
    # confidence), never the page copy that led to it.
    Client,
]

# Column names that would indicate raw third-party content is being stored.
FORBIDDEN_COLUMN_NAMES = {
    "raw_response", "response", "response_text", "answer", "answer_text",
    "body", "content", "text", "raw", "raw_html", "html", "markdown",
    "snippet", "excerpt", "quote", "summary", "description", "context",
    "title", "headline", "meta_description", "copy", "page_text",
    "completion", "output", "message",
}

# Long free-text columns are how raw content gets stored in practice. Facts are
# short and bounded: a domain is <=253, an entity name <=200.
MAX_STRING_LENGTH_FOR_FACTS = 2048


@pytest.mark.parametrize("model", FACTS_ONLY_MODELS, ids=lambda m: m.__tablename__)
def test_no_column_named_like_raw_content(model: type[Base]) -> None:
    offending = {
        c.name for c in model.__table__.columns if c.name.lower() in FORBIDDEN_COLUMN_NAMES
    }
    assert not offending, (
        f"{model.__tablename__} has column(s) {sorted(offending)} whose names indicate "
        f"raw third-party content. ip-safety.md #7 permits facts only: booleans, "
        f"counts, ordinals, domains, URLs, entity names, and structural signals. "
        f"If a feature seems to need the raw text, STOP and flag it."
    )


@pytest.mark.parametrize("model", FACTS_ONLY_MODELS, ids=lambda m: m.__tablename__)
def test_no_unbounded_text_columns(model: type[Base]) -> None:
    """A TEXT column is an open invitation to paste an answer into it."""
    offending = []
    for column in model.__table__.columns:
        type_ = column.type
        if isinstance(type_, Text):
            offending.append(f"{column.name} (TEXT)")
        elif isinstance(type_, String) and (type_.length or 10**9) > MAX_STRING_LENGTH_FOR_FACTS:
            offending.append(f"{column.name} (VARCHAR({type_.length}))")
    assert not offending, (
        f"{model.__tablename__} has unbounded/oversized text column(s) {offending}. "
        f"Facts are short and bounded. See ip-safety.md #7."
    )


def test_engine_result_stores_a_digest_not_the_answer() -> None:
    """Change detection without retention.

    Epic 12 needs to know an answer CHANGED. It does not need to know what it
    said, so a hash is stored instead of the text.
    """
    columns = {c.name: c for c in EngineResult.__table__.columns}
    assert "response_digest" in columns
    assert columns["response_digest"].type.length == 64  # sha256 hex


def test_citations_store_location_not_content() -> None:
    """URLs and domains are permitted; a page's title or blurb is not."""
    names = {c.name for c in Citation.__table__.columns}
    assert {"source_domain", "source_url", "source_type"} <= names
    assert "title" not in names
    assert "snippet" not in names


def test_competitors_store_identity_not_marketing_copy() -> None:
    names = {c.name for c in Competitor.__table__.columns}
    assert {"name", "domain"} <= names
    for forbidden in ("description", "tagline", "summary", "positioning", "about"):
        assert forbidden not in names


def test_technical_audit_stores_structural_signals_only() -> None:
    """Schema TYPE NAMES and counts are signals; page copy is not."""
    names = {c.name for c in TechnicalAudit.__table__.columns}
    assert {"schema_types", "h1_count", "word_count"} <= names
    for forbidden in ("meta_description", "page_title", "html", "content"):
        assert forbidden not in names


def test_prompts_may_hold_text_because_the_text_is_ours() -> None:
    """The deliberate exception, asserted so it stays deliberate.

    Prompt text is generated by us (Epic 4) from the client's industry. It is
    our own content, so storing it is permitted — unlike anything the engines
    return in response to it.
    """
    from avp_api.models import Prompt

    assert isinstance(Prompt.__table__.c.text.type, Text)
    assert Prompt.__tablename__ not in {m.__tablename__ for m in FACTS_ONLY_MODELS}


# ---------------------------------------------------------------------------
# Epic 2 — the intake crawl is where third-party content enters the process.
# ---------------------------------------------------------------------------


def test_client_stores_classification_conclusions_not_page_content() -> None:
    """Client holds derived facts only."""
    names = {c.name for c in Client.__table__.columns}
    # The conclusions we do keep.
    assert {"industry", "industry_niche", "brand_name", "industry_confidence"} <= names
    # Things that would mean page copy had been retained.
    for forbidden in (
        "page_text", "homepage_text", "meta_description", "tagline",
        "about_text", "crawl_html", "raw_html", "extract", "rationale",
    ):
        assert forbidden not in names, f"Client.{forbidden} would retain page content"


def test_classifier_rationale_is_never_persisted() -> None:
    """The model's reasoning is a debug aid, not a stored field.

    `IndustryClassification.rationale` exists so prompt tuning is debuggable.
    It must not reach the database or any response body — otherwise the product
    accumulates model-authored prose about third-party sites with no policy
    covering it.
    """
    from avp_api.schemas.client import ClientDetailOut, ClientOut
    from avp_api.services.classify import ClassificationOutcome, IndustryClassification

    assert "rationale" in IndustryClassification.model_fields
    assert "rationale" not in ClassificationOutcome.model_fields
    assert "rationale" not in ClientOut.model_fields
    assert "rationale" not in ClientDetailOut.model_fields
    assert "rationale" not in {c.name for c in Client.__table__.columns}


def test_crawl_result_is_not_a_database_model() -> None:
    """The object holding page text must have no persistence path.

    CrawlResult carries `text_extract` — real third-party page content. It is a
    plain dataclass on purpose: no SQLAlchemy mapping, no table, no way to
    session.add() it by accident.
    """
    from avp_api.services.crawl import CrawlResult, CrawlSignals

    assert not hasattr(CrawlResult, "__table__")
    assert not hasattr(CrawlResult, "__tablename__")
    assert not hasattr(CrawlSignals, "__table__")
    mapped = {m.class_ for m in Base.registry.mappers}
    assert CrawlResult not in mapped
    assert CrawlSignals not in mapped


def test_crawl_summary_response_cannot_carry_page_text() -> None:
    """The API projection of a crawl exposes facts only."""
    from avp_api.schemas.client import CrawlSummaryOut

    fields = set(CrawlSummaryOut.model_fields)
    assert "text_extract" not in fields
    for forbidden in ("text", "content", "html", "extract", "titles", "body"):
        assert forbidden not in fields, f"CrawlSummaryOut.{forbidden} leaks page content"
    # What it may expose: counts, booleans, URLs, schema type names.
    assert {"pages_fetched", "schema_types", "word_count", "urls_fetched"} <= fields


def test_redacted_crawl_log_view_excludes_text() -> None:
    """Structured logs are a durable store too."""
    from avp_api.services.crawl import CrawlResult, CrawlSignals

    result = CrawlResult(
        signals=CrawlSignals(final_url="https://x.example", registrable_domain="x.example"),
        text_extract="SOME COPYRIGHTED PAGE COPY THAT MUST NOT BE LOGGED",
    )
    rendered = repr(result.redacted())
    assert "COPYRIGHTED" not in rendered
    assert "text_extract" not in result.redacted()


# ---------------------------------------------------------------------------
# Epic 3 — competitor detection reads search results AND engine answers.
# Both are third-party content; only names, domains and counts may survive.
# ---------------------------------------------------------------------------


def test_serp_and_cocitation_results_are_not_database_models() -> None:
    """The objects holding third-party text must have no persistence path."""
    from avp_api.services.cocitation import CoCitationHit, CoCitationResult
    from avp_api.services.serp import SerpHit, SerpResult

    mapped = {m.class_ for m in Base.registry.mappers}
    for cls in (SerpResult, SerpHit, CoCitationResult, CoCitationHit):
        assert cls not in mapped, f"{cls.__name__} must not be an ORM model"
        assert not hasattr(cls, "__table__")
        assert not hasattr(cls, "__tablename__")


def test_cocitation_schema_cannot_carry_answer_text() -> None:
    """The structured-output contract has no free-text field.

    An engine's prose is not ours to store. The schema is the enforcement point:
    if there is nowhere to put answer text, it cannot be persisted by accident.
    """
    from avp_api.services.cocitation import CoCitationAnswer, CoCitedBrand

    assert set(CoCitedBrand.model_fields) == {"name", "domain"}
    assert set(CoCitationAnswer.model_fields) == {"brands", "subject_named"}
    for forbidden in ("answer", "text", "response", "content", "snippet", "rationale"):
        assert forbidden not in CoCitationAnswer.model_fields
        assert forbidden not in CoCitedBrand.model_fields


def test_serp_titles_are_transient_and_never_logged() -> None:
    """SERP titles are publisher copy — held in memory, never persisted."""
    from avp_api.services.serp import SerpResult

    result = SerpResult(query="q", titles=["SOME PUBLISHER HEADLINE THAT MUST NOT PERSIST"])
    rendered = repr(result.redacted())
    assert "PUBLISHER HEADLINE" not in rendered
    assert "titles" not in result.redacted()


def test_cocitation_redacted_log_view_excludes_brand_detail() -> None:
    from avp_api.services.cocitation import CoCitationResult

    view = CoCitationResult(prompt="p").redacted()
    assert set(view) == {"prompt", "hits", "subject_named", "ok", "error_code"}


def test_competitor_tables_store_only_names_domains_and_counts() -> None:
    """Competitor rows carry identity and evidence counts — never copy."""
    from avp_api.models import Competitor, CompetitorSet

    competitor_cols = {c.name for c in Competitor.__table__.columns}
    for forbidden in (
        "description", "tagline", "summary", "positioning", "snippet",
        "title", "about", "copy", "answer_text", "excerpt",
    ):
        assert forbidden not in competitor_cols, f"Competitor.{forbidden} would store copy"

    set_cols = {c.name for c in CompetitorSet.__table__.columns}
    for forbidden in ("raw_results", "serp_payload", "answers", "responses", "snippets"):
        assert forbidden not in set_cols, (
            f"CompetitorSet.{forbidden} would store third-party content"
        )


def test_competitor_response_schemas_expose_facts_only() -> None:
    from avp_api.schemas.competitor import CompetitorOut, CompetitorSetOut

    competitor_fields = set(CompetitorOut.model_fields)
    assert {"name", "domain", "rank", "corroborated"} <= competitor_fields
    for forbidden in ("description", "snippet", "title", "answer", "text", "summary"):
        assert forbidden not in competitor_fields
        assert forbidden not in set(CompetitorSetOut.model_fields)


def test_serp_error_paths_never_log_the_request_url() -> None:
    """The SerpApi request URL contains the API key as a query parameter.

    Logging a failing response body or URL would put the key in the log stream,
    so the module must never do it. Checked by source inspection because the
    failure only shows up in production logs, where it is too late.
    """
    import inspect

    from avp_api.services import serp as serp_module

    source = inspect.getsource(serp_module)
    assert "response.text" not in source, "SerpApi response bodies may echo the API key"
    assert "response.url" not in source, "the SerpApi request URL contains the API key"


# ---------------------------------------------------------------------------
# Epic 4 — engine answers are third-party content. Only facts may survive.
# ---------------------------------------------------------------------------


def test_engine_answer_is_not_a_database_model() -> None:
    """The object holding a live engine answer must have no persistence path."""
    from avp_api.services.engines import CitedSource, EngineAnswer

    mapped = {m.class_ for m in Base.registry.mappers}
    for cls in (EngineAnswer, CitedSource):
        assert cls not in mapped
        assert not hasattr(cls, "__table__")


def test_engine_answer_redacted_view_excludes_the_answer() -> None:
    from avp_api.models.engine_result import Engine
    from avp_api.services.engines import EngineAnswer

    result = EngineAnswer(
        engine=Engine.CLAUDE, engine_version="v", prompt_text="q",
        text="SOME ENGINE PROSE THAT MUST NOT BE LOGGED OR STORED",
    )
    rendered = repr(result.redacted())
    assert "ENGINE PROSE" not in rendered
    assert "text" not in result.redacted()


def test_response_digest_replaces_storing_the_answer() -> None:
    """Change-detection without retention.

    A digest lets two scans be compared for "did the answer change?" without
    keeping either answer, which is the whole reason the column exists.
    """
    from avp_api.models import EngineResult

    columns = {c.name for c in EngineResult.__table__.columns}
    assert "response_digest" in columns
    for forbidden in (
        "response_text", "answer", "answer_text", "raw_response", "body",
        "content", "excerpt", "snippet", "summary",
    ):
        assert forbidden not in columns, f"EngineResult.{forbidden} would retain the answer"


def test_engine_result_response_schema_exposes_facts_only() -> None:
    from avp_api.schemas.scan import BrandMentionOut, CitationOut, EngineResultOut

    fields = set(EngineResultOut.model_fields)
    assert {"mentioned", "position", "prominence", "sentiment", "response_digest"} <= fields
    for forbidden in ("text", "answer", "response", "content", "snippet", "body"):
        assert forbidden not in fields
        assert forbidden not in set(CitationOut.model_fields)
        assert forbidden not in set(BrandMentionOut.model_fields)


def test_citation_and_brand_mention_store_identity_not_copy() -> None:
    from avp_api.models import BrandMention, Citation

    citation_cols = {c.name for c in Citation.__table__.columns}
    assert {"source_domain", "source_url", "source_type"} <= citation_cols
    for forbidden in ("title", "snippet", "excerpt", "description", "text", "quote"):
        assert forbidden not in citation_cols, f"Citation.{forbidden} would store publisher copy"

    mention_cols = {c.name for c in BrandMention.__table__.columns}
    assert {"entity_name", "entity_domain", "position"} <= mention_cols
    for forbidden in ("context", "sentence", "quote", "snippet", "excerpt"):
        assert forbidden not in mention_cols, f"BrandMention.{forbidden} would store answer text"


def test_search_result_titles_are_never_read_into_citations() -> None:
    """Web-search blocks carry titles and page snippets — publisher copy.

    Only the URL and its registrable domain are taken. Verified by source
    inspection because the alternative is noticing it in a database months on.
    """
    import inspect

    from avp_api.services import engines as engines_module

    source = inspect.getsource(engines_module._extract_citations)
    for forbidden in ('"title"', "'title'", ".title", "page_age", "encrypted_content"):
        assert forbidden not in source, f"citation extraction reads {forbidden}"


def test_prompt_text_is_the_documented_exception() -> None:
    """Prompt.text is OUR generated question, not third-party content.

    Recorded explicitly so the exception stays deliberate: if a future change
    ever populated Prompt.text from a scraped source, this test is where the
    reasoning lives to be re-examined.
    """
    from avp_api.models import Prompt

    assert "text" in {c.name for c in Prompt.__table__.columns}


def test_sentiment_schema_cannot_carry_answer_text() -> None:
    from avp_api.services.extraction import SentimentJudgement

    assert set(SentimentJudgement.model_fields) == {"sentiment", "confidence"}


# ---------------------------------------------------------------------------
# Epic 5 — scoring is arithmetic over stored facts. Nothing new is exposed,
# but the surface is asserted so a future sub-score cannot quietly widen it.
# ---------------------------------------------------------------------------


def test_score_table_stores_numbers_and_flags_only() -> None:
    from avp_api.models import Score

    columns = {c.name for c in Score.__table__.columns}
    assert {"composite", "mention_rate", "share_of_voice", "citation_strength"} <= columns
    for forbidden in (
        "evidence", "rationale", "explanation", "narrative", "summary",
        "quote", "snippet", "answer", "response", "text", "commentary",
    ):
        assert forbidden not in columns, f"Score.{forbidden} could hold prose"


def test_score_response_schemas_expose_numbers_only() -> None:
    from avp_api.schemas.score import CompetitorScoreOut, ScoreDetailOut, ScoreOut

    for model in (ScoreOut, ScoreDetailOut, CompetitorScoreOut):
        fields = set(model.model_fields)
        for forbidden in ("text", "answer", "snippet", "quote", "evidence", "rationale"):
            assert forbidden not in fields, f"{model.__name__}.{forbidden} leaks content"


def test_scoring_never_reads_raw_engine_text() -> None:
    """There is no engine text to read — Epic 4 stored a digest instead.

    Asserted at the source level: a future sub-score tempted to re-read an
    answer would have nowhere to read it from, but this makes the intent
    explicit rather than incidental.
    """
    import inspect

    from avp_api.services import scoring, scoring_runner

    for module in (scoring, scoring_runner):
        source = inspect.getsource(module)
        for forbidden in ("response_text", "answer_text", "raw_response", ".text"):
            assert forbidden not in source, f"{module.__name__} touches {forbidden}"


def test_scoring_makes_no_provider_calls() -> None:
    """scoring-spec.md rule 4 — the LLM is never in the scoring path.

    Sentiment is read from EngineResult, where Epic 4 persisted it. If scoring
    could re-classify, re-scoring would stop being reproducible and the whole
    determinism guarantee would be void.
    """
    import inspect

    from avp_api.services import scoring, scoring_runner

    for module in (scoring, scoring_runner):
        source = inspect.getsource(module)
        for forbidden in ("anthropic", "httpx", "messages.create", "messages.parse", "serpapi"):
            assert forbidden not in source, f"{module.__name__} references {forbidden}"


def test_inputs_digest_is_a_hash_not_a_payload() -> None:
    """The digest fingerprints inputs without retaining them."""
    from avp_api.models import Score

    column = Score.__table__.columns["inputs_digest"]
    assert column.type.length == 64, "SHA-256 hex, not a serialised payload"


# ---------------------------------------------------------------------------
# Epic 6 — the technical audit crawls the CLIENT'S OWN site, but the
# facts-only discipline is identical: presence, counts, type names, dates.
# ---------------------------------------------------------------------------


def test_audit_signals_are_not_a_database_model() -> None:
    from avp_api.services.technical_audit import AuditSignals

    mapped = {m.class_ for m in Base.registry.mappers}
    assert AuditSignals not in mapped
    assert not hasattr(AuditSignals, "__table__")


def test_technical_audit_table_stores_facts_only() -> None:
    from avp_api.models import TechnicalAudit

    columns = {c.name for c in TechnicalAudit.__table__.columns}
    assert {"schema_types", "has_sitemap", "h1_count", "content_age_days"} <= columns
    for forbidden in (
        "html", "body", "page_text", "title", "meta_description", "description",
        "og_title", "og_description", "content", "snippet", "excerpt", "raw",
    ):
        assert forbidden not in columns, f"TechnicalAudit.{forbidden} would store page copy"


def test_audit_check_stores_a_code_not_prose() -> None:
    from avp_api.models import TechnicalAuditCheck

    columns = {c.name for c in TechnicalAuditCheck.__table__.columns}
    assert "detail_code" in columns
    for forbidden in ("detail", "message", "description", "explanation", "text", "note"):
        assert forbidden not in columns, f"TechnicalAuditCheck.{forbidden} invites prose"


def test_audit_response_schemas_expose_no_page_content() -> None:
    from avp_api.schemas.audit import AuditCheckOut, TechnicalAuditOut

    for model in (TechnicalAuditOut, AuditCheckOut):
        fields = set(model.model_fields)
        for forbidden in (
            "html", "body", "text", "title", "meta_description", "description",
            "og_title", "content", "snippet", "excerpt",
        ):
            assert forbidden not in fields, f"{model.__name__}.{forbidden} leaks page copy"
    # Presence and counts are permitted; the values behind them are not.
    assert {"has_sitemap", "schema_types", "h1_count"} <= set(TechnicalAuditOut.model_fields)


def test_audit_crawler_reads_only_presence_not_values() -> None:
    """The page evaluate() must not pull meta or OG tag CONTENT.

    Reading `content` off a meta description and storing it would be the exact
    violation ip-safety.md #7 describes. Checked at source level because the
    boundary is one line of JavaScript.
    """
    import inspect

    from avp_api.services import technical_audit as module

    source = inspect.getsource(module.audit_site)
    # Presence checks are `!!document.querySelector(...)`; a value read would be
    # `.getAttribute('content')` on a description or og: tag.
    assert "hasMetaDescription: !!document.querySelector" in source
    assert "og:" in source and "querySelectorAll" in source, "OG tags counted, not read"
    for forbidden in ("innerHTML", "outerHTML", "document.body.innerHTML"):
        assert forbidden not in source, f"crawler reads {forbidden}"


def test_only_dates_are_taken_from_json_ld() -> None:
    """JSON-LD carries headlines, author names and article bodies.

    The freshness extractor must read datePublished/dateModified and nothing
    else — a regex over the whole blob that happened to capture text would be a
    quiet violation.
    """
    from avp_api.services.technical_audit import _extract_structured_date

    blob = (
        '{"@type":"Article","headline":"SECRET HEADLINE TEXT",'
        '"articleBody":"SECRET BODY COPY","datePublished":"2026-01-15"}'
    )
    result = _extract_structured_date(blob)
    assert result is not None
    assert result.year == 2026 and result.month == 1 and result.day == 15
    assert "SECRET" not in str(result)


# ---------------------------------------------------------------------------
# Epic 7 — the first epic that RENDERS collected facts rather than only
# storing them. The database rule is unchanged; what is new is that the
# absence of answer text becomes UI-visible, so the report PROJECTION is
# asserted here as well as the tables behind it.
# ---------------------------------------------------------------------------


def test_report_projection_exposes_no_third_party_prose() -> None:
    """Every field the report can render is a fact.

    Checked over every schema in the module rather than a hand-picked list, so
    a field added to any of them later is caught rather than missed.
    """
    import inspect

    from avp_api.schemas import report as report_schemas
    from avp_api.schemas.common import ApiModel

    forbidden = {
        "text", "answer", "answer_text", "response", "response_text", "snippet",
        "excerpt", "quote", "body", "content", "html", "raw", "description",
        "tagline", "summary", "positioning", "about", "title", "headline",
        "context", "sentence", "commentary", "narrative", "rationale",
        "meta_description", "copy",
    }
    checked = 0
    for _name, obj in inspect.getmembers(report_schemas, inspect.isclass):
        if not (issubclass(obj, ApiModel) and obj is not ApiModel):
            continue
        if obj.__module__ != report_schemas.__name__:
            continue  # re-exported from another epic's module, asserted there
        checked += 1
        leaks = forbidden & set(obj.model_fields)
        assert not leaks, f"{obj.__name__}.{sorted(leaks)} could render third-party prose"
    assert checked >= 10, "the sweep should cover the whole report module"


def test_report_evidence_is_a_domain_and_a_link_never_a_quotation() -> None:
    """ip-safety.md #7: link out to a source, never reproduce it."""
    from avp_api.schemas.report import CitedDomainOut

    fields = set(CitedDomainOut.model_fields)
    assert {"domain", "citations", "sample_url"} <= fields
    for forbidden in ("title", "snippet", "excerpt", "text", "quote", "description"):
        assert forbidden not in fields, f"CitedDomainOut.{forbidden} would quote the source"


def test_report_competitors_carry_identity_and_numbers_only() -> None:
    """A competitor is shown by name and domain. Nothing describes them."""
    from avp_api.schemas.report import ReportCompetitorOut

    fields = set(ReportCompetitorOut.model_fields)
    assert {"name", "domain", "rank"} <= fields
    for forbidden in ("description", "tagline", "summary", "positioning", "about", "snippet"):
        assert forbidden not in fields, f"ReportCompetitorOut.{forbidden} would render copy"


def test_report_audit_findings_carry_a_code_not_a_sentence() -> None:
    """The fix beat resolves codes through OUR OWN string table.

    Storing or returning a sentence would put model- or crawler-authored prose
    about a third-party site into the product with no policy covering it.
    """
    from avp_api.schemas.report import ReportAuditFindingOut

    fields = set(ReportAuditFindingOut.model_fields)
    assert "detail_code" in fields
    for forbidden in ("detail", "message", "explanation", "note", "advice", "recommendation"):
        assert forbidden not in fields, f"ReportAuditFindingOut.{forbidden} invites prose"


def test_report_service_never_reaches_for_answer_text() -> None:
    """There is nothing to reach for — but the intent is made explicit.

    EngineResult has no text-bearing column, so a report tempted to show "what
    the engine said" would have no source for it. Asserted at the source level
    because Epic 7 is where that absence first becomes visible in a UI.
    """
    import inspect

    from avp_api.services import report as module

    source = inspect.getsource(module)
    for forbidden in (
        "response_text", "answer_text", "raw_response", ".answer", ".snippet",
        ".excerpt", "text_extract",
    ):
        assert forbidden not in source, f"report service touches {forbidden}"


def test_engine_result_has_no_text_column_for_a_report_to_render() -> None:
    """The Epic 7 restatement of the Epic 4 guarantee.

    Epic 7's brief asks for this to be verified explicitly rather than assumed,
    because it is the first time the absence is user-visible rather than a
    database fact. Asserted over the actual column types, not a name list.
    """
    from sqlalchemy import String, Text

    from avp_api.models import EngineResult

    for column in EngineResult.__table__.columns:
        if isinstance(column.type, Text):
            raise AssertionError(f"EngineResult.{column.name} is TEXT — it could hold an answer")
        if isinstance(column.type, String):
            # response_digest (64) and engine_version (120) are the only strings.
            assert column.type.length is not None and column.type.length <= 120, (
                f"EngineResult.{column.name} is long enough to hold prose"
            )


# ---------------------------------------------------------------------------
# Epic 8 — the generated fix list.
#
# Every guard above this line protects an OUTPUT: a column that must not exist,
# a schema field that must not be exposed, a log line that must not carry
# prose. Epic 8 is the first module whose boundary is on the INPUT — it builds
# a prompt, and a prompt is where scraped material would leak in, not out.
# There was no test of that kind anywhere in this repo before this block.
# ---------------------------------------------------------------------------


def test_action_item_is_the_documented_free_text_exception() -> None:
    """ActionItem holds prose and is deliberately NOT in FACTS_ONLY_MODELS.

    Every other table stores somebody else's material as facts. This one stores
    OUR OWN recommendations, so `title` and an unbounded `detail` are correct
    (models/action_item.py:1-9). Stated as a test so the exemption is a
    decision on the record rather than an omission someone later "fixes".
    """
    from avp_api.models import ActionItem

    assert ActionItem not in FACTS_ONLY_MODELS
    assert "title" in ActionItem.__table__.c
    assert "detail" in ActionItem.__table__.c


def test_the_fix_prompt_is_built_from_facts_only() -> None:
    """The prompt-construction path must not reach for third-party text.

    Source inspection, because a leak here shows up as a paid request that
    already happened. Same technique as `_extract_citations` in Epic 4 and
    `audit_site` in Epic 6, applied to the function rather than the module so
    an unrelated helper cannot dilute it.
    """
    import inspect

    from avp_api.services import fix_generator

    source = inspect.getsource(fix_generator.build_fix_prompt)
    for forbidden in (
        "text_extract", "answer_text", "response_text", "raw_response",
        ".snippet", ".excerpt", ".titles", "answer.text", "description",
        "tagline", "page_text", "innerHTML",
    ):
        assert forbidden not in source, f"fix prompt construction reads {forbidden}"


def test_the_fix_prompt_names_the_facts_it_is_allowed_to_use() -> None:
    """A POSITIVE source assertion, per Epic 6's `audit_site` guard.

    Asserting only the absence of bad names passes vacuously if the function is
    gutted. These are the constructions that make the prompt facts-only, and
    they must be literally present.
    """
    import inspect

    from avp_api.services import fix_generator

    source = inspect.getsource(fix_generator.build_fix_prompt)
    assert "facts.domain" in source, "the prompt must identify the subject by domain"
    assert "dim.subscore" in source and "dim.gap" in source, "gaps are numbers"
    assert "candidate.detail_code" in source, "audit findings enter as a code, not a sentence"


def test_the_fix_prompt_carries_no_line_that_is_not_a_whitelisted_fact() -> None:
    """Every line of the built prompt must match a known fact label.

    The categorical form of the guard, and the one Epic 5.1 argues for: a
    canary test catches the canary, whereas this catches the class. Adding an
    interpolation that carries page copy, a citation title or a competitor
    description means adding a line whose label is not below — which fails here
    rather than shipping.
    """
    from decimal import Decimal

    from avp_api.services.fix_generator import (
        DimensionFact,
        FixFacts,
        build_candidates,
        build_fix_prompt,
    )

    allowed_prefixes = (
        "Subject brand:", "Website:", "Industry (classified automatically",
        "Niche:", "Visibility score:", "Measurement caveats:",
        "Dimension scores (", "Competitors detected,", "Answer coverage:",
        "Citation coverage:", "Most-cited domains:", "Site structure signals:",
        "Write one fix for each",
    )

    facts = FixFacts(
        domain="helpscout.com",
        brand_name="Help Scout",
        industry="customer support software",
        niche="shared inbox",
        composite=Decimal("58.24"),
        formula_version="v1.1",
        degradation_flags=["NO_AUTHORITY_DATA"],
        dimensions=[
            DimensionFact(
                key="citation_strength",
                weight=Decimal("20.00"),
                subscore=Decimal("3.70"),
                gap=Decimal("19.26"),
            )
        ],
        competitor_names=[("Zendesk", "zendesk.com")],
        answers_analysed=6,
        answers_naming_subject=6,
        citations_total=45,
        citations_to_subject=3,
        top_cited_domains=[("eesel.ai", 6)],
        schema_types=["Corporation", "WebSite"],
        word_count=877,
        h1_count=1,
        indexable=True,
        has_sitemap=True,
    )
    # Every field must carry a value. A second negative control proved why: a
    # line emitted only `if facts.competitor_description` is invisible to this
    # sweep when the field defaults to None, so the guard would have inspected
    # a prompt the injected branch never reached. Asserting over
    # dataclasses.fields means a newly added field fails HERE, unset, rather
    # than passing unexamined.
    import dataclasses

    unset = [
        f.name for f in dataclasses.fields(facts) if getattr(facts, f.name) in (None, [], "")
    ]
    assert not unset, f"give {unset} a value — an unset field hides its prompt line"

    candidates = build_candidates(
        facts.dimensions, [("schema_faq", "warn", "NO_FAQ_SCHEMA")]
    )
    lines = [line for line in build_fix_prompt(facts, candidates).splitlines() if line.strip()]

    # A sweep that covers nothing passes vacuously (Epic 7's `checked >= 10`).
    assert len(lines) >= 14, f"only {len(lines)} lines — the prompt did not build"

    for line in lines:
        if line.startswith("- "):
            continue  # list items under a whitelisted heading
        assert line.startswith(allowed_prefixes), f"unwhitelisted prompt line: {line!r}"


def test_the_facts_bundle_has_no_field_that_could_hold_prose() -> None:
    """`FixFacts` is where a leak would have to land to reach the prompt.

    A dataclasses.fields() name sweep, the same shape as Epic 6's
    `test_signals_carry_no_page_content`. Enforced by the type, so a future
    edit that adds `competitor_description` fails here before it can be
    interpolated anywhere.
    """
    import dataclasses

    from avp_api.services.fix_generator import FixFacts

    names = {f.name for f in dataclasses.fields(FixFacts)}
    forbidden = (
        "text", "answer", "response", "snippet", "excerpt", "quote", "body",
        "content", "html", "raw", "description", "tagline", "summary",
        "positioning", "about", "title", "headline", "copy", "prose", "blurb",
    )
    # Matched as a SUBSTRING of the field name, not by exact equality. A
    # negative control proved why: `competitor_description` passes an exact-set
    # sweep containing "description" without difficulty, and a leak field will
    # always be named for what it holds plus a qualifier. Recorded in
    # docs/build-log.md under Epic 8's negative controls.
    # A field may only carry a forbidden word if its TYPE cannot hold prose.
    # `answers_analysed` and `answers_naming_subject` are ints — they count
    # engine answers rather than holding one. Keying the exemption on the
    # annotation rather than on a name allowlist means `answer_excerpt: str`
    # cannot be waved through the same way.
    countable = {"int", "bool", "Decimal"}
    leaks = sorted(
        f.name
        for f in dataclasses.fields(FixFacts)
        if any(word in f.name for word in forbidden)
        and not any(t in str(f.type) for t in countable)
    )
    assert not leaks, f"FixFacts.{leaks} could carry third-party prose"
    assert len(names) >= 15, "the sweep must actually cover the bundle"


def test_the_facts_bundle_is_not_a_database_model() -> None:
    """Transient, like CrawlResult and AuditSignals before it."""
    from avp_api.models import Base
    from avp_api.services.fix_generator import FixCandidate, FixFacts

    for cls in (FixFacts, FixCandidate):
        assert not hasattr(cls, "__table__")
        assert not hasattr(cls, "__tablename__")
        assert cls not in {m.class_ for m in Base.registry.mappers}


def test_the_facts_redacted_log_view_collapses_entities_to_counts() -> None:
    """Competitor names are facts we may store; a log stream is still not where
    they belong. Same `redacted()` discipline as crawl, serp and cocitation."""
    from avp_api.services.fix_generator import FixFacts

    facts = FixFacts(
        domain="helpscout.com",
        competitor_names=[("CANARY BRAND", "canary.example")],
        top_cited_domains=[("CANARY DOMAIN", 3)],
    )
    view = facts.redacted()
    assert "CANARY" not in repr(view)
    assert view["competitors"] == 1, "a count, not the names"
    assert set(view) == {
        "domain", "dimensions", "competitors", "cited_domains", "schema_types"
    }


def test_model_reasoning_is_never_persisted_or_returned() -> None:
    """The Epic 2 `rationale` chain, applied to Epic 8's two reason fields.

    The model is asked why it chose a priority and an effort, because a model
    that has to justify the letter picks it less arbitrarily. That reasoning is
    working, not product: it must not reach a table, a response schema, or the
    page.
    """
    import dataclasses

    from avp_api.models import ActionItem
    from avp_api.schemas.action_item import ActionItemListOut, ActionItemOut
    from avp_api.services.fix_generator import GeneratedFix, PersistableFix

    assert "priority_reason" in GeneratedFix.model_fields
    assert "effort_reason" in GeneratedFix.model_fields

    persistable = {f.name for f in dataclasses.fields(PersistableFix)}
    for leaked in ("priority_reason", "effort_reason", "rationale"):
        assert leaked not in persistable
        assert leaked not in ActionItemOut.model_fields
        assert leaked not in ActionItemListOut.model_fields
        assert leaked not in ActionItem.__table__.c


def test_the_generated_fix_schema_cannot_carry_third_party_text() -> None:
    """Exact-equality lock, per the CoCitationAnswer and SentimentJudgement
    guards. A field added here is a field a model can fill with anything."""
    from avp_api.services.fix_generator import GeneratedFix, GeneratedFixSet

    assert set(GeneratedFix.model_fields) == {
        "candidate_id", "title", "detail", "priority", "effort",
        "priority_reason", "effort_reason",
    }
    assert set(GeneratedFixSet.model_fields) == {"fixes"}


def test_the_fix_generator_never_reads_a_table_holding_third_party_material() -> None:
    """Source inspection over both Epic 8 modules, per the Epic 5 scoring guard.

    Epic 4 stored a digest instead of the answer and Citation has no title
    column, so there is nothing to read — this makes the intent explicit rather
    than incidental, which is the point of the technique.
    """
    import inspect

    from avp_api.services import fix_generator, fix_runner

    for module in (fix_generator, fix_runner):
        source = inspect.getsource(module)
        for forbidden in (
            "response_text", "answer_text", "raw_response", ".snippet",
            ".excerpt", "text_extract", "response_digest",
        ):
            assert forbidden not in source, f"{module.__name__} touches {forbidden}"


def test_action_item_response_schemas_expose_no_third_party_prose() -> None:
    """ActionItemOut carries `title` and `detail` legitimately. It must not
    carry anything sourced from a competitor, a publisher or an engine."""
    from avp_api.schemas.action_item import ActionItemListOut, ActionItemOut

    forbidden = {
        "text", "answer", "answer_text", "response", "response_text", "snippet",
        "excerpt", "quote", "body", "content", "html", "raw", "tagline",
        "positioning", "about", "meta_description", "copy", "page_title",
    }
    checked = 0
    for schema in (ActionItemOut, ActionItemListOut):
        checked += 1
        leaks = forbidden & set(schema.model_fields)
        assert not leaks, f"{schema.__name__}.{sorted(leaks)} could render third-party prose"
    assert checked == 2


# ---------------------------------------------------------------------------
# Epic 3.6 — competitor manual override.
#
# Placed after Epic 8 because that is when it shipped, not where it sits in the
# numbering. Epic 3's guards above cover the tables and the READ schemas, which
# is everything that existed then: detection wrote the rows and the API only
# ever handed them back. Epic 3.6 turns the override endpoint into a reachable,
# user-facing write path, so the REQUEST schema becomes an ip-safety surface for
# the first time — an operator typing into a form is the one input to this
# system that no upstream extractor has already reduced to facts.
# ---------------------------------------------------------------------------


def test_the_override_request_can_carry_only_a_name_and_a_domain() -> None:
    """Exact-field lock on the operator's input.

    ip-safety.md #7 permits "names of entities mentioned" and the domains that
    were cited. A competitor an operator names is the same kind of fact as one
    detection found, and gets the same fields — no more. Locked by equality
    rather than a forbidden list so that ADDING a field fails here, which is
    the direction the risk actually runs: nobody will name it `tagline`, they
    will name it `note` or `context` and mean the same thing.
    """
    from avp_api.schemas.competitor import CompetitorInput, ReplaceCompetitorsRequest

    assert set(CompetitorInput.model_fields) == {"name", "domain"}
    assert set(ReplaceCompetitorsRequest.model_fields) == {"competitors"}


def test_the_override_request_bounds_what_can_be_typed_into_it() -> None:
    """A fact-shaped field must be fact-sized.

    `name` and `domain` are bounded to the column widths. Without a bound a
    form field is a free-text field with extra steps, and the first thing
    pasted into an unbounded "brand name" box is a positioning line.
    """
    from avp_api.schemas.competitor import CompetitorInput

    limits = {
        name: [m for m in field.metadata if hasattr(m, "max_length")]
        for name, field in CompetitorInput.model_fields.items()
    }
    for name, found in limits.items():
        assert found, f"CompetitorInput.{name} has no max_length"
        assert found[0].max_length <= MAX_STRING_LENGTH_FOR_FACTS, (
            f"CompetitorInput.{name} is long enough to hold prose"
        )


def test_competitor_schemas_expose_no_prose_field_anywhere_in_the_module() -> None:
    """Module-wide sweep, per Epic 7's report-schema guard.

    The two hand-picked assertions in Epic 3's block covered the schemas that
    existed then. A sweep covers the ones that do not exist yet, which is the
    only kind that keeps working.
    """
    import inspect

    from avp_api.schemas import competitor as competitor_schemas
    from avp_api.schemas.common import ApiModel

    forbidden = {
        "text", "answer", "answer_text", "response", "response_text", "snippet",
        "excerpt", "quote", "body", "content", "html", "raw", "description",
        "tagline", "summary", "positioning", "about", "title", "headline",
        "note", "context", "commentary", "rationale", "copy", "meta_description",
    }
    checked = 0
    for _name, obj in inspect.getmembers(competitor_schemas, inspect.isclass):
        if not issubclass(obj, ApiModel) or obj is ApiModel:
            continue
        if obj.__module__ != competitor_schemas.__name__:
            continue  # re-exported from another epic's module, asserted there
        checked += 1
        leaks = forbidden & set(obj.model_fields)
        assert not leaks, f"{obj.__name__}.{sorted(leaks)} could carry competitor copy"
    assert checked >= 4, f"only {checked} schemas swept — the sweep found nothing"


def test_the_override_writer_copies_only_identity_onto_the_row() -> None:
    """Source inspection of the override endpoint.

    The request schema being narrow is necessary but not sufficient: the writer
    is what decides which of those fields reach a column. Asserted positively —
    that `name` and `domain` are the only request values read — because an
    absence-only check passes against a writer that has been rewritten to do
    something else entirely.
    """
    import inspect

    from avp_api.routers import competitors as module

    source = inspect.getsource(module.replace_competitors)
    assert "item.name" in source, "the writer must take the operator's name"
    assert "item.domain" in source, "the writer must take the operator's domain"
    for forbidden in (
        "item.description", "item.note", "item.summary", "item.tagline",
        "item.context", "item.title", "response.text", "snippet",
    ):
        assert forbidden not in source, f"the override writer reads {forbidden}"


def test_a_manually_added_competitor_is_stored_exactly_like_a_detected_one() -> None:
    """No column exists that only a manual row could populate.

    The point of the ip-safety rule is that provenance changes nothing about
    what may be STORED. If an override could carry a field detection cannot,
    that field would by definition be something no extractor produced — which
    is the definition of prose in this system.
    """
    from avp_api.models import Competitor
    from avp_api.schemas.competitor import CompetitorInput

    columns = {c.name for c in Competitor.__table__.columns}
    assert set(CompetitorInput.model_fields) <= columns, (
        "the override request carries a field the competitor table has no home for"
    )


def test_a_suppression_records_the_fact_and_never_the_reason() -> None:
    """`is_suppressed` is a boolean, and must stay one.

    The obvious next field after "the operator removed this" is "why", and the
    honest answer is usually a sentence about a competitor — "they're a
    listicle site, not a vendor", "acquired last year". That is exactly the
    third-party characterisation ip-safety.md #7 keeps out of this system, and
    it would arrive through the one input no extractor has reduced to facts.

    The boolean itself is already covered by the parametrized sweeps at the top
    of this file, because `Competitor` is in FACTS_ONLY_MODELS. This asserts the
    shape of the thing those sweeps would let through: a `suppression_reason`
    String(200) is short enough to pass the length check and not named in the
    forbidden list.
    """
    from sqlalchemy import Boolean

    from avp_api.models import Competitor

    columns = Competitor.__table__.columns
    assert isinstance(columns["is_suppressed"].type, Boolean), (
        "is_suppressed must stay a boolean — a string here would be a free-text "
        "note about a competitor"
    )
    for forbidden in (
        "suppression_reason", "removal_reason", "removed_because", "reason",
        "override_reason", "operator_note", "justification", "comment",
    ):
        assert forbidden not in columns, (
            f"Competitor.{forbidden} would store an operator's prose about a rival"
        )


def test_the_set_has_one_definition_of_which_competitors_are_real() -> None:
    """Every read path must go through `active_competitors`.

    A suppressed row is a tombstone. Seven call sites iterate the competitor
    collection — scoring, the report (x2), prompt seeding, engine extraction,
    fix generation and the API — and a filter copied seven times is a filter
    that will eventually disagree with itself. Asserted by source inspection
    because the failure mode is silent: a missed filter means a struck rival
    reappears in exactly one surface, which is worse than reappearing in all of
    them because nobody would believe the bug report.
    """
    import inspect

    from avp_api.services import fix_runner, report, scan_runner, scoring_runner

    for module in (report, scoring_runner, scan_runner, fix_runner):
        source = inspect.getsource(module)
        assert "competitor_set.competitors" not in source, (
            f"{module.__name__} reads the raw collection — it must use "
            "active_competitors, or suppressed rows leak into it"
        )
        assert "active_competitors" in source, (
            f"{module.__name__} does not read the competitor set through "
            "active_competitors"
        )
