/**
 * Contract tests over the generated OpenAPI types.
 *
 * These guard the pipeline itself: that generation ran, that it covers the
 * endpoints the frontend depends on, and that the conventions fixed in
 * docs/api-contracts.md actually hold in the emitted schema. A drifted or
 * stale api.gen.ts fails here rather than in a browser.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const spec = JSON.parse(
  readFileSync(fileURLToPath(new URL('../openapi.json', import.meta.url)), 'utf8'),
);
const generated = readFileSync(
  fileURLToPath(new URL('../src/api.gen.ts', import.meta.url)),
  'utf8',
);

test('openapi.json is a 3.1 document', () => {
  assert.match(spec.openapi, /^3\.1/);
});

test('every endpoint is under the /api/v1 base path', () => {
  for (const path of Object.keys(spec.paths)) {
    assert.ok(path.startsWith('/api/v1'), `${path} is outside /api/v1`);
  }
});

test('paths use kebab-case segments', () => {
  for (const path of Object.keys(spec.paths)) {
    for (const segment of path.split('/').filter(Boolean)) {
      if (segment.startsWith('{')) continue;
      assert.ok(
        !/[A-Z_]/.test(segment),
        `path segment "${segment}" in ${path} is not kebab-case`,
      );
    }
  }
});

test('the endpoints the web app depends on are present', () => {
  for (const required of [
    '/api/v1/auth/sign-up',
    '/api/v1/auth/login',
    '/api/v1/auth/logout',
    '/api/v1/auth/me',
    '/api/v1/dashboard',
    '/api/v1/health',
  ]) {
    assert.ok(spec.paths[required], `missing endpoint ${required}`);
  }
});

test('response bodies are camelCase', () => {
  const props = Object.keys(spec.components.schemas.UserOut.properties);
  assert.ok(props.includes('fullName'));
  assert.ok(props.includes('lastLoginAt'));
  assert.ok(!props.some((p) => p.includes('_')), `snake_case leaked: ${props}`);
});

test('generation ran and produced the expected surface', () => {
  assert.match(generated, /auto-generated by openapi-typescript/);
  for (const name of ['UserOut', 'AgencyOut', 'MeOut', 'DashboardOut', 'SignUpRequest']) {
    assert.ok(generated.includes(name), `generated types missing ${name}`);
  }
});

test('no password field is ever returned in a response schema', () => {
  for (const [name, schema] of Object.entries(spec.components.schemas)) {
    if (!name.endsWith('Out')) continue;
    const props = Object.keys(schema.properties ?? {});
    assert.ok(
      !props.some((p) => /password|hash|secret/i.test(p)),
      `${name} exposes a credential field: ${props}`,
    );
  }
});

test('score fields are nullable so INSUFFICIENT_DATA is representable', () => {
  // scoring-spec.md: an unrunnable scan is null, never 0.
  const composite = spec.components.schemas.ScanSummaryOut.properties.compositeScore;
  const json = JSON.stringify(composite);
  assert.ok(json.includes('null'), `compositeScore is not nullable: ${json}`);
});

// --- Epic 2: intake & classification ------------------------------------

test('intake endpoints are present', () => {
  for (const required of [
    '/api/v1/clients',
    '/api/v1/clients/{clientId}',
    '/api/v1/clients/{clientId}/reclassify',
  ]) {
    assert.ok(spec.paths[required], `missing endpoint ${required}`);
  }
});

test('path parameters are camelCase, matching the documented convention', () => {
  const op = spec.paths['/api/v1/clients/{clientId}'].get;
  assert.deepEqual(
    op.parameters.map((p) => p.name),
    ['clientId'],
  );
});

test('industry is nullable so an ambiguous classification is representable', () => {
  // The rule the epic hinges on: a low-confidence result stores NULL rather
  // than a guess, because a wrong industry silently poisons Epics 3 and 4.
  const industry = spec.components.schemas.ClientOut.properties.industry;
  assert.ok(JSON.stringify(industry).includes('null'), 'industry must be nullable');
});

test('classification status enumerates the undetermined outcomes', () => {
  const schemas = spec.components.schemas;
  const ref = schemas.ClientOut.properties.classificationStatus;
  const name = (ref.$ref ?? ref.allOf?.[0]?.$ref ?? '').split('/').pop();
  const values = schemas[name]?.enum ?? [];
  assert.deepEqual(
    [...values].sort(),
    ['ambiguous', 'classified', 'pending', 'unclassifiable'],
  );
});

test('confidence score is a string-encoded decimal, not a JSON number', () => {
  // NUMERIC(4,3) in Postgres. A JSON number is an IEEE double, which would
  // reintroduce float error at the transport layer.
  const score = spec.components.schemas.ClientOut.properties.industryConfidenceScore;
  const json = JSON.stringify(score);
  assert.ok(json.includes('string'), `expected string encoding, got ${json}`);
});

test('the crawl projection exposes facts, never page content', () => {
  // ip-safety.md #7 — mirrored on the API surface, not just in the database.
  const props = Object.keys(spec.components.schemas.CrawlSummaryOut.properties);
  for (const forbidden of ['textExtract', 'text', 'content', 'html', 'titles', 'body']) {
    assert.ok(!props.includes(forbidden), `CrawlSummaryOut.${forbidden} leaks page content`);
  }
  assert.ok(props.includes('schemaTypes'));
  assert.ok(props.includes('pagesFetched'));
});

test('no response schema exposes the classifier rationale', () => {
  for (const [name, schema] of Object.entries(spec.components.schemas)) {
    if (!name.endsWith('Out')) continue;
    const props = Object.keys(schema.properties ?? {});
    assert.ok(!props.includes('rationale'), `${name} exposes the model's rationale`);
  }
});

// --- Epic 4: prompt generation & engine execution -----------------------

test('scan endpoints are present', () => {
  for (const required of [
    '/api/v1/clients/{clientId}/scans',
    '/api/v1/scans/{scanId}',
    '/api/v1/scans/{scanId}/results',
    '/api/v1/scans/{scanId}/prompts',
  ]) {
    assert.ok(spec.paths[required], `missing endpoint ${required}`);
  }
});

test('engine enum includes both engines actually wired up', () => {
  const values = spec.components.schemas.Engine.enum;
  assert.ok(values.includes('claude'), 'parametric engine missing');
  assert.ok(values.includes('claude_search'), 'grounded engine missing');
});

test('prompt intents cover the buyer journey', () => {
  assert.deepEqual(
    [...spec.components.schemas.PromptIntent.enum].sort(),
    ['awareness', 'bottom_funnel', 'comparison'],
  );
});

test('engine results expose facts, never the answer', () => {
  // ip-safety.md #7 — mirrored on the API surface, not only in the database.
  const props = Object.keys(spec.components.schemas.EngineResultOut.properties);
  for (const forbidden of ['text', 'answer', 'response', 'content', 'snippet', 'body', 'excerpt']) {
    assert.ok(!props.includes(forbidden), `EngineResultOut.${forbidden} leaks the answer`);
  }
  // What it may expose.
  for (const required of ['mentioned', 'position', 'sentiment', 'responseDigest', 'brandsMentioned']) {
    assert.ok(props.includes(required), `EngineResultOut.${required} missing`);
  }
});

test('citations carry identity, not publisher copy', () => {
  const props = Object.keys(spec.components.schemas.CitationOut.properties);
  for (const forbidden of ['title', 'snippet', 'excerpt', 'description', 'text', 'quote']) {
    assert.ok(!props.includes(forbidden), `CitationOut.${forbidden} leaks publisher copy`);
  }
  assert.ok(props.includes('sourceDomain'));
  assert.ok(props.includes('sourceType'));
});

test('brand mentions carry no surrounding context', () => {
  const props = Object.keys(spec.components.schemas.BrandMentionOut.properties);
  for (const forbidden of ['context', 'sentence', 'quote', 'snippet', 'excerpt', 'text']) {
    assert.ok(!props.includes(forbidden), `BrandMentionOut.${forbidden} leaks answer text`);
  }
});

test('prominence and sentiment confidence are string-encoded decimals', () => {
  // NUMERIC in Postgres. A JSON number is an IEEE double.
  const props = spec.components.schemas.EngineResultOut.properties;
  for (const field of ['prominence', 'sentimentConfidence']) {
    assert.ok(
      JSON.stringify(props[field]).includes('string'),
      `${field} must cross the wire as a string`,
    );
  }
});

test('answered_no_mention is a distinct status, not an error', () => {
  // A no-mention is the product's core finding; it must not be conflated with
  // a failed call.
  const values = spec.components.schemas.EngineResultStatus.enum;
  assert.ok(values.includes('answered_no_mention'));
  assert.ok(values.includes('error'));
});

// --- Epic 5: scoring ------------------------------------------------------

test('score endpoints are present', () => {
  for (const required of [
    '/api/v1/scans/{scanId}/score',
    '/api/v1/scans/{scanId}/scores',
  ]) {
    assert.ok(spec.paths[required], `missing endpoint ${required}`);
  }
});

test('every score value is a string-encoded decimal, never a JSON number', () => {
  // A JSON number is an IEEE double — precisely what scoring-spec.md rule 3
  // forbids for the weighted sum.
  const props = spec.components.schemas.ScoreOut.properties;
  for (const field of [
    'composite', 'mentionRate', 'shareOfVoice',
    'citationStrength', 'sentiment', 'technicalFoundation',
  ]) {
    const json = JSON.stringify(props[field]);
    assert.ok(json.includes('string'), `${field} must be string-encoded, got ${json}`);
  }
});

test('composite is nullable so an unrunnable scan is not a zero', () => {
  const json = JSON.stringify(spec.components.schemas.ScoreOut.properties.composite);
  assert.ok(json.includes('null'), 'composite must be nullable');
});

test('score status distinguishes scored from insufficient_data', () => {
  assert.deepEqual(
    [...spec.components.schemas.ScoreStatus.enum].sort(),
    ['insufficient_data', 'scored'],
  );
});

test('competitor scores carry no composite', () => {
  // Sentiment is subject-only and Technical Foundation is Epic 6, so 25% of the
  // weight has no per-competitor input. A composite on a different weight basis
  // would not be comparable to the subject's.
  const props = Object.keys(spec.components.schemas.CompetitorScoreOut.properties);
  assert.ok(!props.includes('composite'), 'competitors must not carry a composite');
  assert.ok(props.includes('mentionRate'));
  assert.ok(props.includes('shareOfVoice'));
  assert.ok(props.includes('citationStrength'));
});

test('score exposes provenance for auditability', () => {
  const props = Object.keys(spec.components.schemas.ScoreOut.properties);
  for (const required of [
    'formulaVersion', 'weights', 'excludedDimensions',
    'degradationFlags', 'inputsDigest',
  ]) {
    assert.ok(props.includes(required), `ScoreOut.${required} missing`);
  }
});

test('score schemas expose no prose fields', () => {
  // ip-safety.md #7 mirrored on the API surface.
  for (const name of ['ScoreOut', 'ScoreDetailOut', 'CompetitorScoreOut']) {
    const props = Object.keys(spec.components.schemas[name].properties ?? {});
    for (const forbidden of ['text', 'answer', 'snippet', 'quote', 'evidence', 'rationale']) {
      assert.ok(!props.includes(forbidden), `${name}.${forbidden} leaks content`);
    }
  }
});

// --- Epic 6: technical audit ---------------------------------------------

test('audit endpoints are present', () => {
  assert.ok(spec.paths['/api/v1/scans/{scanId}/audit']);
});

test('audit exposes per-check pass/fail with a detail code', () => {
  // §7's acceptance criterion is per-check pass/fail + detail.
  const props = Object.keys(spec.components.schemas.AuditCheckOut.properties);
  assert.ok(props.includes('checkKey'));
  assert.ok(props.includes('status'));
  assert.ok(props.includes('detailCode'));
  assert.deepEqual(
    [...spec.components.schemas.CheckStatus.enum].sort(),
    ['error', 'fail', 'not_applicable', 'pass', 'warn'],
  );
});

test('audit status distinguishes failed from partial', () => {
  // A site we could not read must not look like a site with no markup.
  assert.deepEqual(
    [...spec.components.schemas.AuditStatus.enum].sort(),
    ['failed', 'ok', 'partial'],
  );
});

test('technicalFoundation is a nullable string-encoded decimal', () => {
  const json = JSON.stringify(
    spec.components.schemas.TechnicalAuditOut.properties.technicalFoundation,
  );
  assert.ok(json.includes('string'), 'must be string-encoded, not a JSON number');
  assert.ok(json.includes('null'), 'null when the site could not be read');
});

test('audit exposes presence and counts, never page content', () => {
  // ip-safety.md #7 mirrored on the API surface.
  const props = Object.keys(spec.components.schemas.TechnicalAuditOut.properties);
  for (const forbidden of [
    'html', 'body', 'text', 'title', 'metaDescription', 'description',
    'ogTitle', 'content', 'snippet', 'excerpt',
  ]) {
    assert.ok(!props.includes(forbidden), `TechnicalAuditOut.${forbidden} leaks page copy`);
  }
  for (const required of ['hasSitemap', 'schemaTypes', 'h1Count', 'isIndexable']) {
    assert.ok(props.includes(required), `TechnicalAuditOut.${required} missing`);
  }
});

test('inpMs exists but is documented as unmeasurable by a crawler', () => {
  const props = spec.components.schemas.TechnicalAuditOut.properties;
  assert.ok('inpMs' in props, 'INP field must exist for future field data');
  assert.ok(JSON.stringify(props.inpMs).includes('null'));
});

// --- report (Epic 7) ------------------------------------------------------
// The report is the first surface that RENDERS collected facts. These tests
// guard the wire contract the report screen is built against.

const report = spec.components.schemas.ReportOut.properties;

test('the report endpoint is present', () => {
  assert.ok(spec.paths['/api/v1/scans/{scanId}/report']);
});

test('the report carries all five beats worth of material', () => {
  for (const field of ['score', 'dimensions', 'competitorSet', 'proof', 'audit']) {
    assert.ok(report[field], `ReportOut.${field} is missing`);
  }
});

test('score, competitorSet and audit are nullable so degraded scans are representable', () => {
  // A scan that was never scored, never had competitors detected, or was never
  // audited must be renderable as such — not as a zero and not as a crash.
  for (const field of ['score', 'competitorSet', 'audit']) {
    const schema = JSON.stringify(report[field]);
    assert.match(schema, /"type":"null"/, `ReportOut.${field} must be nullable`);
  }
});

test('a report dimension can be excluded without being a zero', () => {
  const dimension = spec.components.schemas.ReportDimensionOut.properties;
  assert.ok(dimension.included);
  assert.ok(dimension.exclusionReason);
  // subscore is nullable: an excluded dimension has no value, which is a
  // different claim from a measured zero.
  assert.match(JSON.stringify(dimension.subscore), /"type":"null"/);
});

test('report decimals are string-encoded, never JSON numbers', () => {
  const dimension = spec.components.schemas.ReportDimensionOut.properties;
  assert.match(JSON.stringify(dimension.weight), /"type":"string"/);
  assert.match(JSON.stringify(dimension.subscore), /"type":"string"/);
});

test('report competitors carry identity and comparable sub-scores, no composite', () => {
  const competitor = spec.components.schemas.ReportCompetitorOut.properties;
  assert.ok(competitor.name && competitor.domain);
  // Sentiment and Technical Foundation have no per-competitor input, so a
  // "competitor composite" would be computed on a different weight basis and
  // would not be comparable to the subject's.
  assert.equal(competitor.composite, undefined);
});

test('report evidence exposes cited domains and links, never quoted text', () => {
  const cited = spec.components.schemas.CitedDomainOut.properties;
  assert.ok(cited.domain && cited.citations && cited.sampleUrl);
  for (const forbidden of ['title', 'snippet', 'excerpt', 'text', 'quote']) {
    assert.equal(cited[forbidden], undefined, `CitedDomainOut.${forbidden} would quote a source`);
  }
});

test('no report schema exposes a prose field', () => {
  const forbidden = [
    'text', 'answer', 'response', 'snippet', 'excerpt', 'quote', 'body',
    'content', 'description', 'tagline', 'summary', 'narrative', 'rationale',
  ];
  for (const [name, schema] of Object.entries(spec.components.schemas)) {
    if (!name.startsWith('Report') && !['CitedDomainOut', 'MentionShareOut', 'EngineCoverageOut'].includes(name)) {
      continue;
    }
    for (const field of forbidden) {
      assert.equal(
        schema.properties?.[field], undefined,
        `${name}.${field} could render third-party prose`,
      );
    }
  }
});

test('report generation is a GET — it presents, it does not compute', () => {
  const operations = Object.keys(spec.paths['/api/v1/scans/{scanId}/report']);
  assert.deepEqual(operations, ['get']);
});

// --- action list (Epic 8) -------------------------------------------------

test('the fix generation endpoints are present', () => {
  const operations = Object.keys(spec.paths['/api/v1/scans/{scanId}/fixes']);
  // POST generates (it spends a model call); GET reads back.
  assert.deepEqual([...operations].sort(), ['get', 'post']);
});

test('an action item is keyed back to the candidate it enriches', () => {
  // The whole design: generated copy merges onto the client's derived list by
  // key. Without source + sourceKey the report cannot match them up.
  const props = Object.keys(spec.components.schemas.ActionItemOut.properties);
  assert.ok(props.includes('source'));
  assert.ok(props.includes('sourceKey'));
  assert.deepEqual([...spec.components.schemas.ActionItemSource.enum].sort(), ['audit', 'gap']);
});

test('an action item carries reasoned priority and effort', () => {
  // §7 Epic 8: "priority + effort estimation per fix".
  const props = Object.keys(spec.components.schemas.ActionItemOut.properties);
  assert.ok(props.includes('priority'));
  assert.ok(props.includes('effort'));
  assert.deepEqual([...spec.components.schemas.Priority.enum].sort(), ['high', 'low', 'medium']);
  assert.deepEqual([...spec.components.schemas.Effort.enum].sort(), ['L', 'M', 'S']);
});

test('pointsUpside stays a nullable string-encoded decimal', () => {
  // An audit fix has no measurable point value. Null, never zero, and never a
  // JSON number — same decimal convention as every other score on the wire.
  const prop = spec.components.schemas.ActionItemOut.properties.pointsUpside;
  const variants = prop.anyOf ?? [prop];
  assert.ok(variants.some((v) => v.type === 'null'));
  assert.ok(variants.some((v) => v.type === 'string'));
  assert.ok(!variants.some((v) => v.type === 'number'));
});

test('the generator records which model wrote the copy', () => {
  // prompt_sets.generated_by precedent: a change in wording quality must be
  // attributable to a model version.
  assert.ok('generatedBy' in spec.components.schemas.ActionItemOut.properties);
  assert.ok('generatedBy' in spec.components.schemas.ActionItemListOut.properties);
});

test('a failed generation is a status, not an empty list', () => {
  // "nothing to fix" and "generation failed" are different things to tell a
  // viewer, exactly as with score status vs a null composite.
  const props = Object.keys(spec.components.schemas.ActionItemListOut.properties);
  assert.ok(props.includes('status'));
  assert.ok(props.includes('reasonCode'));
});

test('the report carries the generated fix list', () => {
  assert.ok('actionItems' in spec.components.schemas.ReportOut.properties);
});

test('no action item schema exposes third-party prose', () => {
  // `title` and `detail` are ours (ip-safety.md #7, models/action_item.py).
  // Nothing sourced from a competitor, publisher or engine may sit beside them.
  const forbidden = [
    'text', 'answer', 'response', 'snippet', 'excerpt', 'quote', 'body',
    'content', 'html', 'raw', 'tagline', 'summary', 'positioning', 'about',
    'metaDescription', 'rationale', 'priorityReason', 'effortReason',
  ];
  for (const name of ['ActionItemOut', 'ActionItemListOut']) {
    for (const field of forbidden) {
      assert.equal(
        spec.components.schemas[name].properties?.[field], undefined,
        `${name}.${field} could render third-party prose`,
      );
    }
  }
});
