"""score excluded_dimensions to jsonb

Revision ID: 6ebd897b3cf8
Revises: d3c33ad15d58
Created: 2026-08-21 15:31:45.681380
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '6ebd897b3cf8'
down_revision: str | None = 'd3c33ad15d58'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Adjusted by hand. Autogenerate emitted a bare ALTER TYPE, which Postgres
    # rejects: there is no implicit cast from varchar[] to jsonb.
    #
    # The conversion DISCARDS any existing values rather than mapping them.
    # That is correct, not lossy-by-accident: the old column was a list of
    # excluded dimension NAMES, and the new one is {dimension: reason}. The
    # reasons never existed, so there is nothing to migrate them from — an
    # invented reason would be worse than an empty map. No rows exist at the
    # time of writing in any case.
    op.execute("ALTER TABLE scores ALTER COLUMN excluded_dimensions DROP DEFAULT")
    op.execute(
        "ALTER TABLE scores ALTER COLUMN excluded_dimensions "
        "TYPE JSONB USING '{}'::jsonb"
    )
    op.execute(
        "ALTER TABLE scores ALTER COLUMN excluded_dimensions SET DEFAULT '{}'::jsonb"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Same reasoning in reverse: the reason codes have no representation in a
    # bare name array, so the values are dropped rather than half-translated.
    op.execute("ALTER TABLE scores ALTER COLUMN excluded_dimensions DROP DEFAULT")
    op.execute(
        "ALTER TABLE scores ALTER COLUMN excluded_dimensions "
        "TYPE VARCHAR(40)[] USING '{}'::varchar(40)[]"
    )
    op.execute(
        "ALTER TABLE scores ALTER COLUMN excluded_dimensions "
        "SET DEFAULT '{}'::character varying[]"
    )
