"""ai crawler access

Revision ID: 33b576c694d0
Revises: 31524aae82f6
Created: 2026-09-03 15:25:23.152226
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '33b576c694d0'
down_revision: str | None = '31524aae82f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_crawler_access',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('audit_id', sa.String(length=40), nullable=False),
    sa.Column('agent_token', sa.String(length=80), nullable=False),
    sa.Column('vendor', sa.String(length=80), nullable=False),
    sa.Column('purpose', sa.Enum('training', 'search', 'user_action', name='agent_purpose', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('verdict', sa.Enum('allowed', 'blocked', 'unspecified', 'unknown', name='access_verdict', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('rule_source', sa.Enum('explicit', 'wildcard', 'none', 'unreadable', name='rule_source', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('matched_token', sa.String(length=200), nullable=True),
    sa.Column('disallow_rules', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(verdict IN ('unspecified', 'unknown') AND matched_token IS NULL) OR (verdict IN ('allowed', 'blocked') AND matched_token IS NOT NULL)", name=op.f('ck_ai_crawler_access_matched_token_matches_verdict')),
    sa.CheckConstraint('disallow_rules >= 0', name=op.f('ck_ai_crawler_access_disallow_rules_non_negative')),
    sa.ForeignKeyConstraint(['audit_id'], ['technical_audits.id'], name=op.f('fk_ai_crawler_access_audit_id_technical_audits'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_crawler_access')),
    sa.UniqueConstraint('audit_id', 'agent_token', name='uq_ai_crawler_access_audit_agent')
    )
    op.create_index(op.f('ix_ai_crawler_access_audit_id'), 'ai_crawler_access', ['audit_id'], unique=False)
    op.create_index('ix_ai_crawler_access_audit_verdict', 'ai_crawler_access', ['audit_id', 'verdict'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_crawler_access_audit_verdict', table_name='ai_crawler_access')
    op.drop_index(op.f('ix_ai_crawler_access_audit_id'), table_name='ai_crawler_access')
    op.drop_table('ai_crawler_access')
    # ### end Alembic commands ###
