"""competitor detection provenance

Revision ID: 672109d81730
Revises: f0a2acd1e37c
Created: 2026-08-21 10:07:16.894425
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '672109d81730'
down_revision: str | None = 'f0a2acd1e37c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitor_sets', sa.Column('status', sa.Enum('ok', 'weak_signal', 'no_signal', name='detection_status', native_enum=False, create_constraint=True, length=32), nullable=False, server_default='ok'))
    op.add_column('competitor_sets', sa.Column('detection_confidence', sa.Numeric(precision=4, scale=3), nullable=True))
    op.add_column('competitor_sets', sa.Column('serp_queries_run', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('competitor_sets', sa.Column('co_citation_prompts_run', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('competitor_sets', sa.Column('candidates_considered', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('competitor_sets', sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('competitor_sets', sa.Column('used_industry_seed', sa.Boolean(), nullable=False, server_default='false'))
    op.create_check_constraint(op.f('ck_competitor_sets_detection_confidence_range'), 'competitor_sets', 'detection_confidence IS NULL OR (detection_confidence >= 0 AND detection_confidence <= 1)')
    op.add_column('competitors', sa.Column('serp_mentions', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('competitors', sa.Column('co_citation_mentions', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('competitors', sa.Column('corroborated', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('competitors', sa.Column('score', sa.Numeric(precision=7, scale=3), nullable=True))
    # Defaults existed only to backfill existing rows during the ALTER; the
    # application always supplies these values. Dropping them keeps the
    # database matching the model, which `alembic check` verifies.
    op.alter_column('competitor_sets', 'status', server_default=None)
    op.alter_column('competitor_sets', 'serp_queries_run', server_default=None)
    op.alter_column('competitor_sets', 'co_citation_prompts_run', server_default=None)
    op.alter_column('competitor_sets', 'candidates_considered', server_default=None)
    op.alter_column('competitor_sets', 'used_industry_seed', server_default=None)
    op.alter_column('competitors', 'serp_mentions', server_default=None)
    op.alter_column('competitors', 'co_citation_mentions', server_default=None)
    op.alter_column('competitors', 'corroborated', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitors', 'score')
    op.drop_column('competitors', 'corroborated')
    op.drop_column('competitors', 'co_citation_mentions')
    op.drop_column('competitors', 'serp_mentions')
    op.drop_constraint(op.f('ck_competitor_sets_detection_confidence_range'), 'competitor_sets', type_='check')
    op.drop_column('competitor_sets', 'used_industry_seed')
    op.drop_column('competitor_sets', 'detected_at')
    op.drop_column('competitor_sets', 'candidates_considered')
    op.drop_column('competitor_sets', 'co_citation_prompts_run')
    op.drop_column('competitor_sets', 'serp_queries_run')
    op.drop_column('competitor_sets', 'detection_confidence')
    op.drop_column('competitor_sets', 'status')
    # ### end Alembic commands ###
