"""alerts

Revision ID: 31524aae82f6
Revises: 2b8e8aa41f32
Created: 2026-09-02 18:14:21.392278
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '31524aae82f6'
down_revision: str | None = '2b8e8aa41f32'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('client_id', sa.String(length=40), nullable=False),
    sa.Column('agency_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.Enum('visibility_drop', 'sentiment_decline', 'owned_citation_lost', name='alert_kind', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('scan_id', sa.String(length=40), nullable=False),
    sa.Column('baseline_scan_id', sa.String(length=40), nullable=False),
    sa.Column('engine', sa.String(length=40), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], name=op.f('fk_alerts_agency_id_agencies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['baseline_scan_id'], ['scans.id'], name=op.f('fk_alerts_baseline_scan_id_scans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_alerts_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_alerts_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index(op.f('ix_alerts_agency_id'), 'alerts', ['agency_id'], unique=False)
    op.create_index(op.f('ix_alerts_baseline_scan_id'), 'alerts', ['baseline_scan_id'], unique=False)
    op.create_index('ix_alerts_client_acknowledged', 'alerts', ['client_id', 'acknowledged_at'], unique=False)
    op.create_index(op.f('ix_alerts_client_id'), 'alerts', ['client_id'], unique=False)
    op.create_index('ix_alerts_client_id_id', 'alerts', ['client_id', 'id'], unique=False)
    op.create_index(op.f('ix_alerts_scan_id'), 'alerts', ['scan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_scan_id'), table_name='alerts')
    op.drop_index('ix_alerts_client_id_id', table_name='alerts')
    op.drop_index(op.f('ix_alerts_client_id'), table_name='alerts')
    op.drop_index('ix_alerts_client_acknowledged', table_name='alerts')
    op.drop_index(op.f('ix_alerts_baseline_scan_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_agency_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
