"""prompt run sentiment

Two columns on `prompt_run_results`, matching the pair `engine_results` has
carried since Epic 4 — Epic A.

WHY THIS IS A CORRECTION, NOT A FEATURE
----------------------------------------
Epic 9.24 built ad-hoc prompt runs through the same `ask_all` and
`extract_facts` a scan uses, deliberately, so that "does this prompt name my
client?" could not answer differently on the two paths. It then stopped one
step short: the scan path classifies tone and the ad-hoc path did not, so the
same question asked two ways produced different depth. This closes that.

NULLABLE, AND NULL IS THE RIGHT ANSWER FOR EVERY EXISTING ROW. No run in any
database was ever classified, because the pass did not run for them. A backfill
would mean re-asking a model about answers this system deliberately did not
keep — the text is gone, which is the point of the facts-only rule. Every run made
before this migration therefore reads as "tone not measured", which is exactly
what happened.

NULL ALSO MEANS SOMETHING AFTER THIS RUNS, AND IT IS NOT "NEUTRAL".
`classify_sentiment` is called only where the subject was named, so a NULL on a
new row means the engine answered without naming the client. That is a finding,
not a missing value, and `HistorySentimentOut.unclassified` keeps it in its own
bucket rather than folding it into neutral.


Revision ID: 2b8e8aa41f32
Revises: fa9c51c75f78
Created: 2026-09-02 13:40:02.955695
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '2b8e8aa41f32'
down_revision: str | None = 'fa9c51c75f78'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column('prompt_run_results', sa.Column('sentiment', sa.Enum('positive', 'neutral', 'negative', name='prompt_run_sentiment', native_enum=False, create_constraint=True, length=32), nullable=True))
    op.add_column('prompt_run_results', sa.Column('sentiment_confidence', sa.Numeric(precision=4, scale=3), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt_run_results', 'sentiment_confidence')
    op.drop_column('prompt_run_results', 'sentiment')
    # ### end Alembic commands ###
