"""client classification fields

Revision ID: f0a2acd1e37c
Revises: 2db5215d9f95
Created: 2026-08-20 17:52:55.359617
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'f0a2acd1e37c'
down_revision: str | None = '2db5215d9f95'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('industry_niche', sa.String(length=160), nullable=True))
    # server_default is required, not cosmetic: this is a NOT NULL column added
    # to a table that may already hold rows. Without it the ALTER fails on any
    # non-empty clients table. Existing rows predate classification, so
    # 'pending' is the correct backfill — and it satisfies the
    # industry_matches_classification_status constraint below, because those
    # rows have industry IS NULL.
    op.add_column(
        'clients',
        sa.Column(
            'classification_status',
            sa.Enum(
                'pending', 'classified', 'ambiguous', 'unclassifiable',
                name='classification_status', native_enum=False,
                create_constraint=True, length=32,
            ),
            nullable=False,
            server_default='pending',
        ),
    )
    # Drop the default now that existing rows are backfilled. It existed only
    # to make the NOT NULL add possible; the application always supplies the
    # value explicitly. Leaving it would put a default in the database that the
    # model does not declare, which `alembic check` correctly reports as drift.
    op.alter_column('clients', 'classification_status', server_default=None)
    op.add_column('clients', sa.Column('classification_reason_code', sa.String(length=60), nullable=True))
    op.add_column('clients', sa.Column('industry_confidence_score', sa.Numeric(precision=4, scale=3), nullable=True))
    op.add_column('clients', sa.Column('classified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('clients', sa.Column('classifier_model', sa.String(length=80), nullable=True))
    op.create_check_constraint(op.f('ck_clients_industry_confidence_score_range'), 'clients', 'industry_confidence_score IS NULL OR (industry_confidence_score >= 0 AND industry_confidence_score <= 1)')
    op.create_check_constraint(op.f('ck_clients_industry_matches_classification_status'), 'clients', "(classification_status = 'classified' AND industry IS NOT NULL) OR (classification_status <> 'classified' AND industry IS NULL)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_clients_industry_matches_classification_status'), 'clients', type_='check')
    op.drop_constraint(op.f('ck_clients_industry_confidence_score_range'), 'clients', type_='check')
    op.drop_column('clients', 'classifier_model')
    op.drop_column('clients', 'classified_at')
    op.drop_column('clients', 'industry_confidence_score')
    op.drop_column('clients', 'classification_reason_code')
    op.drop_column('clients', 'classification_status')
    op.drop_column('clients', 'industry_niche')
    # ### end Alembic commands ###
