"""initial schema

Revision ID: 2db5215d9f95
Revises: 
Created: 2026-08-20 15:24:30.005239
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '2db5215d9f95'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('seat_limit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('length(slug) >= 2', name=op.f('ck_agencies_slug_min_length')),
    sa.CheckConstraint('seat_limit >= 1', name=op.f('ck_agencies_seat_limit_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agencies')),
    sa.UniqueConstraint('slug', name=op.f('uq_agencies_slug'))
    )
    op.create_index(op.f('ix_agencies_deleted_at'), 'agencies', ['deleted_at'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('agency_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=253), nullable=False),
    sa.Column('kind', sa.Enum('prospect', 'client', 'churned', name='client_kind', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('industry_confidence', sa.String(length=16), nullable=True),
    sa.Column('brand_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], name=op.f('fk_clients_agency_id_agencies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients')),
    sa.UniqueConstraint('agency_id', 'domain', name='uq_clients_agency_id_domain')
    )
    op.create_index(op.f('ix_clients_agency_id'), 'clients', ['agency_id'], unique=False)
    op.create_index('ix_clients_agency_kind', 'clients', ['agency_id', 'kind', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_clients_deleted_at'), 'clients', ['deleted_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('agency_id', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', name='user_role', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('active', 'invited', 'suspended', name='user_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status = 'invited' AND password_hash IS NULL) OR password_hash IS NOT NULL", name=op.f('ck_users_active_user_has_password')),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], name=op.f('fk_users_agency_id_agencies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index(op.f('ix_users_agency_id'), 'users', ['agency_id'], unique=False)
    op.create_index('ix_users_agency_status', 'users', ['agency_id', 'status', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('agency_id', sa.String(length=40), nullable=False),
    sa.Column('invited_by_user_id', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', name='invitation_role', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('token_digest', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], name=op.f('fk_invitations_agency_id_agencies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], name=op.f('fk_invitations_invited_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invitations')),
    sa.UniqueConstraint('token_digest', name=op.f('uq_invitations_token_digest'))
    )
    op.create_index('ix_invitations_agency_email', 'invitations', ['agency_id', 'email'], unique=False)
    op.create_index(op.f('ix_invitations_agency_id'), 'invitations', ['agency_id'], unique=False)
    op.create_index(op.f('ix_invitations_invited_by_user_id'), 'invitations', ['invited_by_user_id'], unique=False)
    op.create_table('scans',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('client_id', sa.String(length=40), nullable=False),
    sa.Column('agency_id', sa.String(length=40), nullable=False),
    sa.Column('requested_by_user_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'partial', 'failed', 'cancelled', name='scan_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('trigger', sa.Enum('manual', 'scheduled', 'bulk', name='scan_trigger', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('formula_version', sa.String(length=40), nullable=False),
    sa.Column('engine_versions', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('prompt_count', sa.Integer(), nullable=False),
    sa.Column('engine_result_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], name=op.f('fk_scans_agency_id_agencies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_scans_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_scans_requested_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scans'))
    )
    op.create_index('ix_scans_agency_created', 'scans', ['agency_id', 'id'], unique=False)
    op.create_index(op.f('ix_scans_agency_id'), 'scans', ['agency_id'], unique=False)
    op.create_index('ix_scans_client_created', 'scans', ['client_id', 'id'], unique=False)
    op.create_index(op.f('ix_scans_client_id'), 'scans', ['client_id'], unique=False)
    op.create_index(op.f('ix_scans_requested_by_user_id'), 'scans', ['requested_by_user_id'], unique=False)
    op.create_index('ix_scans_status', 'scans', ['status'], unique=False)
    op.create_table('action_items',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('scan_id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('high', 'medium', 'low', name='action_priority', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('effort', sa.Enum('S', 'M', 'L', name='action_effort', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'done', 'dismissed', name='action_item_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('dimension_key', sa.String(length=40), nullable=True),
    sa.Column('points_upside', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('points_upside IS NULL OR (points_upside >= 0 AND points_upside <= 100)', name=op.f('ck_action_items_points_upside_range')),
    sa.CheckConstraint('rank >= 1', name=op.f('ck_action_items_rank_positive')),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_action_items_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_items'))
    )
    op.create_index(op.f('ix_action_items_scan_id'), 'action_items', ['scan_id'], unique=False)
    op.create_index('ix_action_items_scan_rank', 'action_items', ['scan_id', 'rank'], unique=False)
    op.create_table('competitor_sets',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('scan_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_competitor_sets_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competitor_sets')),
    sa.UniqueConstraint('scan_id', name='uq_competitor_sets_scan_id')
    )
    op.create_index(op.f('ix_competitor_sets_scan_id'), 'competitor_sets', ['scan_id'], unique=False)
    op.create_table('prompt_sets',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('scan_id', sa.String(length=40), nullable=False),
    sa.Column('generated_by', sa.String(length=120), nullable=True),
    sa.Column('generation_params', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_prompt_sets_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_sets')),
    sa.UniqueConstraint('scan_id', name='uq_prompt_sets_scan_id')
    )
    op.create_index(op.f('ix_prompt_sets_scan_id'), 'prompt_sets', ['scan_id'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('scan_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('scored', 'insufficient_data', name='score_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('composite', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('mention_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('share_of_voice', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('citation_strength', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sentiment', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('technical_foundation', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('formula_version', sa.String(length=40), nullable=False),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('excluded_dimensions', sa.ARRAY(sa.String(length=40)), server_default='{}', nullable=False),
    sa.Column('degradation_flags', sa.ARRAY(sa.String(length=60)), server_default='{}', nullable=False),
    sa.Column('reason_code', sa.String(length=60), nullable=True),
    sa.Column('inputs_digest', sa.String(length=64), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'scored' AND composite IS NOT NULL) OR (status = 'insufficient_data' AND composite IS NULL)", name=op.f('ck_scores_composite_matches_status')),
    sa.CheckConstraint('citation_strength IS NULL OR (citation_strength >= 0 AND citation_strength <= 100)', name=op.f('ck_scores_citation_strength_range')),
    sa.CheckConstraint('composite IS NULL OR (composite >= 0 AND composite <= 100)', name=op.f('ck_scores_composite_range')),
    sa.CheckConstraint('inputs_digest IS NULL OR length(inputs_digest) = 64', name=op.f('ck_scores_inputs_digest_is_sha256')),
    sa.CheckConstraint('mention_rate IS NULL OR (mention_rate >= 0 AND mention_rate <= 100)', name=op.f('ck_scores_mention_rate_range')),
    sa.CheckConstraint('sentiment IS NULL OR (sentiment >= 0 AND sentiment <= 100)', name=op.f('ck_scores_sentiment_range')),
    sa.CheckConstraint('share_of_voice IS NULL OR (share_of_voice >= 0 AND share_of_voice <= 100)', name=op.f('ck_scores_share_of_voice_range')),
    sa.CheckConstraint('technical_foundation IS NULL OR (technical_foundation >= 0 AND technical_foundation <= 100)', name=op.f('ck_scores_technical_foundation_range')),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_scores_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scores')),
    sa.UniqueConstraint('scan_id', 'formula_version', name='uq_scores_scan_formula')
    )
    op.create_index('ix_scores_scan', 'scores', ['scan_id'], unique=False)
    op.create_index(op.f('ix_scores_scan_id'), 'scores', ['scan_id'], unique=False)
    op.create_table('technical_audits',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('scan_id', sa.String(length=40), nullable=False),
    sa.Column('url_audited', sa.String(length=2048), nullable=False),
    sa.Column('pages_crawled', sa.Integer(), nullable=False),
    sa.Column('lcp_ms', sa.Integer(), nullable=True),
    sa.Column('inp_ms', sa.Integer(), nullable=True),
    sa.Column('cls', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('schema_types', sa.ARRAY(sa.String(length=80)), server_default='{}', nullable=False),
    sa.Column('has_organization_schema', sa.Boolean(), nullable=False),
    sa.Column('has_localbusiness_schema', sa.Boolean(), nullable=False),
    sa.Column('has_faq_schema', sa.Boolean(), nullable=False),
    sa.Column('has_product_schema', sa.Boolean(), nullable=False),
    sa.Column('is_indexable', sa.Boolean(), nullable=True),
    sa.Column('robots_allows_crawl', sa.Boolean(), nullable=True),
    sa.Column('has_sitemap', sa.Boolean(), nullable=True),
    sa.Column('canonical_present', sa.Boolean(), nullable=True),
    sa.Column('h1_count', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('content_age_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cls IS NULL OR cls >= 0', name=op.f('ck_technical_audits_cls_non_negative')),
    sa.CheckConstraint('inp_ms IS NULL OR inp_ms >= 0', name=op.f('ck_technical_audits_inp_non_negative')),
    sa.CheckConstraint('lcp_ms IS NULL OR lcp_ms >= 0', name=op.f('ck_technical_audits_lcp_non_negative')),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_technical_audits_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technical_audits')),
    sa.UniqueConstraint('scan_id', name='uq_technical_audits_scan_id')
    )
    op.create_index(op.f('ix_technical_audits_scan_id'), 'technical_audits', ['scan_id'], unique=False)
    op.create_table('competitors',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('competitor_set_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=253), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('detection_source', sa.Enum('serp', 'co_citation', 'manual', name='detection_source', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('signal_count', sa.Integer(), nullable=False),
    sa.Column('is_manual_override', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rank >= 1', name=op.f('ck_competitors_rank_positive')),
    sa.ForeignKeyConstraint(['competitor_set_id'], ['competitor_sets.id'], name=op.f('fk_competitors_competitor_set_id_competitor_sets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competitors')),
    sa.UniqueConstraint('competitor_set_id', 'name', name='uq_competitors_set_name')
    )
    op.create_index(op.f('ix_competitors_competitor_set_id'), 'competitors', ['competitor_set_id'], unique=False)
    op.create_index('ix_competitors_set_rank', 'competitors', ['competitor_set_id', 'rank'], unique=False)
    op.create_table('prompts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('prompt_set_id', sa.String(length=40), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('intent', sa.Enum('awareness', 'comparison', 'bottom_funnel', name='prompt_intent', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_set_id'], ['prompt_sets.id'], name=op.f('fk_prompts_prompt_set_id_prompt_sets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompts')),
    sa.UniqueConstraint('prompt_set_id', 'position', name='uq_prompts_set_position')
    )
    op.create_index(op.f('ix_prompts_prompt_set_id'), 'prompts', ['prompt_set_id'], unique=False)
    op.create_index('ix_prompts_set_intent', 'prompts', ['prompt_set_id', 'intent'], unique=False)
    op.create_table('technical_audit_checks',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('audit_id', sa.String(length=40), nullable=False),
    sa.Column('check_key', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('pass', 'warn', 'fail', 'not_applicable', 'error', name='check_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('detail_code', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['technical_audits.id'], name=op.f('fk_technical_audit_checks_audit_id_technical_audits'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technical_audit_checks')),
    sa.UniqueConstraint('audit_id', 'check_key', name='uq_audit_checks_audit_key')
    )
    op.create_index('ix_audit_checks_audit_status', 'technical_audit_checks', ['audit_id', 'status'], unique=False)
    op.create_index(op.f('ix_technical_audit_checks_audit_id'), 'technical_audit_checks', ['audit_id'], unique=False)
    op.create_table('engine_results',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('scan_id', sa.String(length=40), nullable=False),
    sa.Column('prompt_id', sa.String(length=40), nullable=False),
    sa.Column('engine', sa.Enum('chatgpt', 'perplexity', 'google_ai_overview', 'gemini', 'claude', 'copilot', name='engine', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('engine_version', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('ok', 'answered_no_mention', 'rate_limited', 'error', 'timeout', name='engine_result_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('mentioned', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('prominence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('sentiment', sa.Enum('positive', 'neutral', 'negative', name='sentiment', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('sentiment_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('brands_mentioned', sa.Integer(), nullable=False),
    sa.Column('response_digest', sa.String(length=64), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(mentioned = false AND position IS NULL) OR (mentioned = true)', name=op.f('ck_engine_results_unmentioned_has_no_position')),
    sa.CheckConstraint('brands_mentioned >= 0', name=op.f('ck_engine_results_brands_mentioned_non_negative')),
    sa.CheckConstraint('position IS NULL OR position >= 1', name=op.f('ck_engine_results_position_positive')),
    sa.CheckConstraint('prominence IS NULL OR (prominence >= 0 AND prominence <= 1)', name=op.f('ck_engine_results_prominence_range')),
    sa.CheckConstraint('response_digest IS NULL OR length(response_digest) = 64', name=op.f('ck_engine_results_response_digest_is_sha256')),
    sa.CheckConstraint('sentiment_confidence IS NULL OR (sentiment_confidence >= 0 AND sentiment_confidence <= 1)', name=op.f('ck_engine_results_sentiment_confidence_range')),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], name=op.f('fk_engine_results_prompt_id_prompts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_engine_results_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_engine_results')),
    sa.UniqueConstraint('prompt_id', 'engine', name='uq_engine_results_prompt_engine')
    )
    op.create_index(op.f('ix_engine_results_prompt_id'), 'engine_results', ['prompt_id'], unique=False)
    op.create_index('ix_engine_results_scan_engine', 'engine_results', ['scan_id', 'engine'], unique=False)
    op.create_index(op.f('ix_engine_results_scan_id'), 'engine_results', ['scan_id'], unique=False)
    op.create_index('ix_engine_results_scan_mentioned', 'engine_results', ['scan_id', 'mentioned'], unique=False)
    op.create_table('engine_result_brand_mentions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('engine_result_id', sa.String(length=40), nullable=False),
    sa.Column('entity_name', sa.String(length=200), nullable=False),
    sa.Column('entity_domain', sa.String(length=253), nullable=True),
    sa.Column('is_subject', sa.Boolean(), nullable=False),
    sa.Column('competitor_id', sa.String(length=40), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], name=op.f('fk_engine_result_brand_mentions_competitor_id_competitors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['engine_result_id'], ['engine_results.id'], name=op.f('fk_engine_result_brand_mentions_engine_result_id_engine_results'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_engine_result_brand_mentions')),
    sa.UniqueConstraint('engine_result_id', 'entity_name', name='uq_brand_mentions_result_entity')
    )
    op.create_index('ix_brand_mentions_result_subject', 'engine_result_brand_mentions', ['engine_result_id', 'is_subject'], unique=False)
    op.create_index(op.f('ix_engine_result_brand_mentions_competitor_id'), 'engine_result_brand_mentions', ['competitor_id'], unique=False)
    op.create_index(op.f('ix_engine_result_brand_mentions_engine_result_id'), 'engine_result_brand_mentions', ['engine_result_id'], unique=False)
    op.create_table('engine_result_citations',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('engine_result_id', sa.String(length=40), nullable=False),
    sa.Column('source_domain', sa.String(length=253), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('source_type', sa.Enum('owned', 'competitor', 'directory', 'review', 'editorial', 'social', 'other', name='citation_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('cites_subject', sa.Boolean(), nullable=False),
    sa.Column('competitor_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], name=op.f('fk_engine_result_citations_competitor_id_competitors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['engine_result_id'], ['engine_results.id'], name=op.f('fk_engine_result_citations_engine_result_id_engine_results'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_engine_result_citations'))
    )
    op.create_index('ix_citations_domain', 'engine_result_citations', ['source_domain'], unique=False)
    op.create_index('ix_citations_result_domain', 'engine_result_citations', ['engine_result_id', 'source_domain'], unique=False)
    op.create_index(op.f('ix_engine_result_citations_competitor_id'), 'engine_result_citations', ['competitor_id'], unique=False)
    op.create_index(op.f('ix_engine_result_citations_engine_result_id'), 'engine_result_citations', ['engine_result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_engine_result_citations_engine_result_id'), table_name='engine_result_citations')
    op.drop_index(op.f('ix_engine_result_citations_competitor_id'), table_name='engine_result_citations')
    op.drop_index('ix_citations_result_domain', table_name='engine_result_citations')
    op.drop_index('ix_citations_domain', table_name='engine_result_citations')
    op.drop_table('engine_result_citations')
    op.drop_index(op.f('ix_engine_result_brand_mentions_engine_result_id'), table_name='engine_result_brand_mentions')
    op.drop_index(op.f('ix_engine_result_brand_mentions_competitor_id'), table_name='engine_result_brand_mentions')
    op.drop_index('ix_brand_mentions_result_subject', table_name='engine_result_brand_mentions')
    op.drop_table('engine_result_brand_mentions')
    op.drop_index('ix_engine_results_scan_mentioned', table_name='engine_results')
    op.drop_index(op.f('ix_engine_results_scan_id'), table_name='engine_results')
    op.drop_index('ix_engine_results_scan_engine', table_name='engine_results')
    op.drop_index(op.f('ix_engine_results_prompt_id'), table_name='engine_results')
    op.drop_table('engine_results')
    op.drop_index(op.f('ix_technical_audit_checks_audit_id'), table_name='technical_audit_checks')
    op.drop_index('ix_audit_checks_audit_status', table_name='technical_audit_checks')
    op.drop_table('technical_audit_checks')
    op.drop_index('ix_prompts_set_intent', table_name='prompts')
    op.drop_index(op.f('ix_prompts_prompt_set_id'), table_name='prompts')
    op.drop_table('prompts')
    op.drop_index('ix_competitors_set_rank', table_name='competitors')
    op.drop_index(op.f('ix_competitors_competitor_set_id'), table_name='competitors')
    op.drop_table('competitors')
    op.drop_index(op.f('ix_technical_audits_scan_id'), table_name='technical_audits')
    op.drop_table('technical_audits')
    op.drop_index(op.f('ix_scores_scan_id'), table_name='scores')
    op.drop_index('ix_scores_scan', table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_prompt_sets_scan_id'), table_name='prompt_sets')
    op.drop_table('prompt_sets')
    op.drop_index(op.f('ix_competitor_sets_scan_id'), table_name='competitor_sets')
    op.drop_table('competitor_sets')
    op.drop_index('ix_action_items_scan_rank', table_name='action_items')
    op.drop_index(op.f('ix_action_items_scan_id'), table_name='action_items')
    op.drop_table('action_items')
    op.drop_index('ix_scans_status', table_name='scans')
    op.drop_index(op.f('ix_scans_requested_by_user_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_client_id'), table_name='scans')
    op.drop_index('ix_scans_client_created', table_name='scans')
    op.drop_index(op.f('ix_scans_agency_id'), table_name='scans')
    op.drop_index('ix_scans_agency_created', table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_invitations_invited_by_user_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_agency_id'), table_name='invitations')
    op.drop_index('ix_invitations_agency_email', table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index('ix_users_agency_status', table_name='users')
    op.drop_index(op.f('ix_users_agency_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_clients_deleted_at'), table_name='clients')
    op.drop_index('ix_clients_agency_kind', table_name='clients')
    op.drop_index(op.f('ix_clients_agency_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_agencies_deleted_at'), table_name='agencies')
    op.drop_table('agencies')
    # ### end Alembic commands ###
