"""technical audit status and score

Revision ID: 5e96862c19a1
Revises: 6ebd897b3cf8
Created: 2026-08-22 09:36:23.214285
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '5e96862c19a1'
down_revision: str | None = '6ebd897b3cf8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('technical_audits', sa.Column('status', sa.Enum('ok', 'partial', 'failed', name='audit_status', native_enum=False, create_constraint=True, length=32), nullable=False, server_default='ok'))
    op.add_column('technical_audits', sa.Column('error_code', sa.String(length=64), nullable=True))
    op.add_column('technical_audits', sa.Column('technical_foundation', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('technical_audits', sa.Column('excluded_components', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    op.add_column('technical_audits', sa.Column('audited_at', sa.DateTime(timezone=True), nullable=True))
    # status: the default existed only to backfill during the ALTER; the
    # application always supplies it, and the model declares none. Dropped so
    # the DB matches the model, which `alembic check` verifies.
    #
    # excluded_components KEEPS its default — the model declares
    # server_default="{}" for it, so dropping it here would itself be drift.
    op.alter_column('technical_audits', 'status', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technical_audits', 'audited_at')
    op.drop_column('technical_audits', 'excluded_components')
    op.drop_column('technical_audits', 'technical_foundation')
    op.drop_column('technical_audits', 'error_code')
    op.drop_column('technical_audits', 'status')
    # ### end Alembic commands ###
